### ISSUE TITLE
 why featureString generated from BagOfVisualWords using different BinarySplit instances are different

### ISSUE THREAD

**Issue by weihangChen** [accord-net/framework#104]
I am reading the code related to BagOfVisualWords in classification project, and find that the feature vector returned for the same image is always different, when different binarysplit instances are used. Is it supposed to be random?

when I run the code below, featureString is always different from featureString3

    BinarySplit binarySplit = new BinarySplit(36);
    BinarySplit binarySplit3 = new BinarySplit(36);

    // Create bag-of-words (BoW) with the given algorithm
    var bow = new BagOfVisualWords(binarySplit);
    var bow3 = new BagOfVisualWords(binarySplit3);
    bow.Compute(originalTrainImages1.Values.ToArray());
    bow3.Compute(originalTrainImages1.Values.ToArray());

    Bitmap image = ImageDatas.FirstOrDefault().bitmap;

    string featureString = bow.GetFeatureVector(image).ToString(DefaultArrayFormatProvider.InvariantCulture);
    string featureString3 = bow3.GetFeatureVector(image).ToString(DefaultArrayFormatProvider.InvariantCulture);

**Comment by weihangChen** [comment]
as I read the source code, finds out that the randomness comes from 

"BinarySplit.Compute" when one cluster is splited, anyone can confirm this?


    private static Tuple<double[][], double[][]> split(double[][] cluster,
            KMeans kmeans, double threshold)
        {
            kmeans.Randomize(cluster, useSeeding: false);

            kmeans.Tolerance = threshold;
            kmeans.ComputeInformation = false;

            int[] idx = kmeans.Compute(cluster);

            List<double[]> a = new List<double[]>();
            List<double[]> b = new List<double[]>();

            for (int i = 0; i < idx.Length; i++)
            {
                if (idx[i] == 0)
                    a.Add(cluster[i]);
                else
                    b.Add(cluster[i]);
            }

            return Tuple.Create(a.ToArray(), b.ToArray());
        }

**Comment by cesarsouza** [comment]
Hi Weihang,

The fact is that the K-Means and the BinarySplit algorithms are always initialized with random values. This is expected, as those algorithms always need to start from random points from the dataset in order to converge to a proper solution.

However, may I ask exactly why you would like to produce always the same results in the binary split algorithm? If you are training your model only once, and would like to reuse their results afterwards during different runs of your program, please consider serializing the K-Means or Binary Split algorithms using .NET serialization (or check if there are .Load and .Save methods available for your model and use them if possible).

This way, you would be able to persist your clusterings and generate always the same results if necessary.

Hope it helps!

Best regards,
Cesar

**Comment by weihangChen** [comment]
> The fact is that the K-Means and the BinarySplit algorithms are always initialized with random values.  This is expected, as those algorithms always need to start from random points from the dataset in 
> order to converge to a proper solution.

The first thing that makes me believe that the BinarySplit.compute generates deterministic values in clusterings, is the unit test BinarySplitConstructorTest.cs. I use different binarysplit instances to compute the same double[ ][ ] and saw that the centroids values within clustrings are the same

            double[][] observations = 
            {
                new double[] { -5, -2, -1 },
                new double[] { -5, -5, -6 },
                new double[] {  2,  1,  1 },
                new double[] {  1,  1,  2 },
                new double[] {  1,  2,  2 },
                new double[] {  3,  1,  2 },
                new double[] { 11,  5,  4 },
                new double[] { 15,  5,  6 },
                new double[] { 10,  5,  6 },
            };
           BinarySplit binarySplit = new BinarySplit(3);
           int[] labels = binarySplit.Compute(observations);

           BinarySplit binarySplit1 = new BinarySplit(3);
           int[] labels1 = binarySplit1.Compute(observations);

now, if it is truly random, then the the centroids within clusters between "different runs" should be different, but they are the same series of values

           var surfBow = new BagOfVisualWords(binarySplit);
           surfBow.Compute(originalTrainImages.Values.ToArray());

Thank you so much for letting me know how to keep the training result!!

**Comment by cesarsouza** [comment]
Hi Chen,

The unit tests use a little trick in the beginning in order to make the algorithm always converge to the same solution. The "randomness" in the framework is controlled by a single random generator that can be initialized with a fixed seed. As such, by initializing the generator with a specific seed, the sequence of random numbers used during the calculations will remain the same, even across different algorithm runs.

However, this trick was intended to be used only by the unit tests. In practice, the clustering results must be persisted to disk using the technique I described before.

Hope it helps!

Best regards,
Cesar

**Comment by weihangChen** [comment]
thank you Cesar, I close this now
