### ISSUE TITLE
Is DQN possible?

### ISSUE THREAD

**Issue by FireDragonGameStudio** [accord-net/framework#1067]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - [x ] question
  - [ ] bug report
  - [ ] feature request

**Issue description**
Is it possible to get DQN, maybe as a combination of QLearning and DeepNeuralNetwork?

Best regards

**Comment by cesarsouza** [comment]
Hi @FireDragonGameStudio,

Thanks for opening the issue! However, I am sure proper support for DQNs will not be possible until the [first stages of Keras#](https://github.com/cesarsouza/keras-sharp/) are finished and the first deliverables of that project are available to end users. 

Most likely, it would have been possible to implement DQN with the current Accord.Neuro and QLearning - but the problem is that this implementation would have been too slow for almost any current practical applications being pursued at this time.

Thus said, Keras# development is not that far behind - in reality, we are waiting for a number of features to be implemented by either TensorFlow or CNTK such that we could provide features such as DQNs in the short future.

Regards,
Cesar

**Comment by FireDragonGameStudio** [comment]
Hy @cesarsouza ,
thank you for your explanation. I'm looking forward to play around with DQN as soon as it will be available. :)

Best regards :)

**Comment by cesarsouza** [comment]
Cool! If you'd like, please watch the Keras# project for updates - we are pending some updates from the TensorFlow project but once they implement the missing APIs it should finally become possible to start developing DQNs with Keras# and Accord.NET.
