### ISSUE TITLE
Consider build portable class libraries for wider use

### ISSUE THREAD

**Issue by zmLGBBM** [accord-net/framework#121]
As for the launch of VS2015, more and more developers tend to try out newly introduced cross-platform framework, xamarin, and also the new universal windows platform(UWP).

Portable class library is considered as the most widely used technique for code sharing. With portable class library support, Accord.NET could be used in a much wider developing world. And it doesn't seem so hard, does it? ;-)

Thanks for the framework btw.

**Comment by anders9ustafsson** [comment]
I have ported a sub-set of *Accord.NET* to portable class libraries for .NET 4.5+, Windows 8.1, Windows Phone 8.1, Xamarin.iOS and Xamarin Android, [here](https://github.com/cureos/accord). Although not explicitly tested, these libraries should be compatible with the Universal Windows Platform as well. The libraries are also available on *NuGet* if you search for "portable accord".

**Comment by zmLGBBM** [comment]
@anders9ustafsson Thanks for the efforts.
I built a android app using ``regular`` Accord.NET framework with portable class library and just works fine. Although, when using support vector machine, there's no
```
System.ICloneable
```
interface in portable `mscorlib.dll`. So I downloaded Accord.NET's src and modified several files, then put into my own project and it works well.

**Comment by anders9ustafsson** [comment]
Thanks for your input, @zmLGBBM, and great to hear that you got things working well. Do you mean that you have rebuilt Accord.NET specifically for Android, or? That should probably work just fine for non-imaging libraries, since Xamarin.Android Mono and .NET Framework are highly compatible. 

The special thing with the PCL libraries I am providing is that they can also target the *Windows 8.1* (tablet and desktop) and *Windows Phone 8.1* platforms, along with .NET, Xamarin iOS and Android. **And** the imaging based libraries are covered thanks to the *System.Drawing* assembly replacement that I have developed.

**Comment by zmLGBBM** [comment]
@anders9ustafsson Grrrrrreat! I'll definitely try that out some time. Thanks ;-)
