### ISSUE TITLE
Visual Studio 2015

### ISSUE THREAD

**Issue by dlmacedo** [accord-net/framework#153]
Dear friends,

Does anybody tried to open the framework in Visual Studio 2015?

I am trying and getting errors:

Project 'Accord.Tests.Math.Cpp' could not be loaded because it's missing install components. To fix this launch Visual Studio setup with the following selections:
Install Visual C++ 2015 Tools for Windows Desktop

David

**Comment by cesarsouza** [comment]
Hi David!

In order to compile the framework in VS2015, I am almost sure that you will need to have the C++ tools from VS2013 also installed in your system. Please note that you don't have to actually use Visual Studio 2013, you just need to have it installed. You can install the free/community/express versions if you want.

Hope it helps!

Regards,
Cesar

**Comment by cesarsouza** [comment]
Solved in release 3.4.0.
