### ISSUE TITLE
use of ColorSlider in accord -> aforge.net

### ISSUE THREAD

**Issue by gui1664** [accord-net/framework#155]
I can't use any of my previous implementation of Colorslider (works well with Aforge 2.2.5.0 but not with Accord 3.0.2). I can't get rid of : 
"System.ArgumentException" in System.Drawing.dll , Null is not valid for stream. 
it's happens when : ColorSlider slider = new ColorSlider();
Do you have any information why ?
Thanks in advance.

**Comment by cesarsouza** [comment]
Maybe it might be too late for the original poster, but the issue was happening because of the namespace merge with AForge.NET. In order to solve this issue, it might be necessary to remove any serialization happening in the designer (i.e. by going in the the form's .Designer.cs file, finding any lines that seem to be loading ColorSlider properties. Basically, look for lines that have GetResources, GetValue and other deserialization calls and simply remove them. Additionally, rename any AForge.* namespaces to Accord.*, such as AForge.Controls to Accord.Controls.

You might have to close and re-open your form to make it work again.
