### ISSUE TITLE
Add an Example for VideoFileWriter.Open Method (String, Int32, Int32, Rational, VideoCodec, Int32, AudioCodec, Int32, Int32, Int32)

### ISSUE THREAD

**Issue by dogliwei** [accord-net/framework#1626]
Please add an example for VideoFileWriter.Open Method (String, Int32, Int32, Rational, VideoCodec, Int32, AudioCodec, Int32, Int32, Int32).

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: ms-its:C:\Users\Administrator\Desktop\Accord.NET-3.8.0-archive\Docs\Accord.NET.chm::/html/M_Accord_Video_FFMPEG_VideoFileWriter_Open_4.htm

**Comment by Wkalmar** [comment]
Hi.
Since no stuff has been merged into master for the last year I assume that nobody contributes here anymore. Still, as I've found this report by some lucky coincidence I'll use it as a place for a rant.
1. I can't import `Accord.Video.FFMPEG` when using F# project. The code fails to compile because FFMPEG not found. The respective package is installed. When I install this package in C# code everything compiles.
2. Documentation for `VideoFileWriter` class is frustrating. It has no value at all as it does not provide any value beyond what I can figure out with my IDE

I'm wondering:
1. If there are any plans to maintain abovementioned functionality?
2. Where exactly it is located in this vast codebase?
3. In case you don't support it may I use your code as a reference for my own library (if I'll ever devote my time to writing it)?
Thanks in advance
