### ISSUE TITLE
Classification (SVMs) with integers

### ISSUE THREAD

**Issue by danthecomputerguy** [accord-net/framework#166]
I am using the Classification (SVMs) project and it works great with the examples.xls provided, after I made all off the recommended changes in post #133.

But when I try to create machine using my data, which consists of all integers that vary from 1-19973608, it seems to work, but the ram utilization shoots sky high, and it would take forever to finish creating the machine, even with a small sample set.

Any thoughts?  thank you!

**Comment by cesarsouza** [comment]
After almost an year, the refactoring/redesign that would make this possible was finally over and has been made available in Release 3.2. Now SVMs can work with any kind of data, and any kind of kernel. I apologize since it might be already too late for you, but I sincerely hope others could benefit from it in the future.

If anybody needs a special kernel for a specific kind of data, all that is necessary is to create a _struct_ implementing the IKernel<T> namespace, then call one of the SVM learners passing this kernel as the learner's generic parameter.

If memory is a problem, you can also now use the Linear machine learners such as [LinearDualCoordinateDescent](http://accord-framework.net/docs/html/T_Accord_MachineLearning_VectorMachines_Learning_LinearDualCoordinateDescent_2.htm) with any custom kernel and custom data type.

An example is given below:

```
public struct IntLinear : IKernel<int>, ILinear<int>
{
    public double Function(int a, int b)
    {
        return a * b;
    }
}

var learner = new LinearDualCoordinateDescent<IntLinear>();

var svm = learner.Learn(x, y);
```
