### ISSUE TITLE
Text naive bayes classification gives wrong results

### ISSUE THREAD

**Issue by RichardHoly** [accord-net/framework#168]
Hello,
I am trying to work out an example of naive bayes classification of text.
I have found this example by author César Souza:
https://code.google.com/p/accord/source/browse/trunk/Sources/Accord.Tests/Accord.Tests.MachineLearning/Bayes/NaiveBayesTest.cs?spec=svn360&r=360

There is spam/lorem classification of given text strings. In the example the model is trained with the same strings as is later tested. That works. But if I try to compute classification on new strings it gives weird results:

"I decided to sign up for" is classified as "lorem"
"I decided to sign up for the" is classified as "spam"

With my attached test.cs file:
[test.cs.txt](https://github.com/accord-net/framework/files/31965/test.cs.txt)

var test = new AccordTest.Test();
test.ClassifyText();

Is it a library bug or bug in the example?

**Comment by cesarsouza** [comment]
Hi there,

It seems to me that this can be qualified as a bug in the example _and_ an incorrect assumption on how that example can be used. The point is that the learning is being done using only a single instance for each class, which forces the distributions to have very sharp probabilities (i.e. if a string does not contain a word it is expecting for a class, it would be right away discarded as not being of that class). 

Given this, it seems the classifier is classifying not according to which words are in the strings, but rather to how many less incorrect words each example has. Since the training sample for lorem ipsum is way smaller in terms of number of words, this makes the classifier more likely to classify instances as lorem ipsum than spam because of the less room for mistakes.
