### ISSUE TITLE
Are the machine learning implementations multithreaded?

### ISSUE THREAD

**Issue by functionsoft** [accord-net/framework#202]
Hi,

A general question, I am using at present Kernel Support Vector Machines, however it appears to only use a single thread.

Do the machine learning implementations make use of all available cores?  Is there any configuration or samples to make the library multithreaded?

Thanks,

Mike

**Comment by cesarsouza** [comment]
Hi there,

If you are learning a multi-class or multi-label support vector machine using [MulticlassSupportVectorMachine](http://accord-framework.net/docs/html/T_Accord_MachineLearning_VectorMachines_MulticlassSupportVectorMachine_2.htm) or [MultilabelSupportVectorMachine](http://accord-framework.net/docs/html/T_Accord_MachineLearning_VectorMachines_MultilabelSupportVectorMachine_2.htm), then the learning should be multi-threaded by default. You can control the parallelization options through the [ParallelOptions](http://accord-framework.net/docs/html/P_Accord_MachineLearning_VectorMachines_MultilabelSupportVectorMachine_3_ParallelOptions.htm) property in both classes.

However, if you are using learning a single support vector machine, through any of the standard binary learning classes ([SequentialMinimalOptimization](http://accord-framework.net/docs/html/T_Accord_MachineLearning_VectorMachines_Learning_SequentialMinimalOptimization_2.htm), [LinearDualCoordinateDescent](http://accord-framework.net/docs/html/T_Accord_MachineLearning_VectorMachines_Learning_LinearDualCoordinateDescent_2.htm), [LinearNewtonMethod](http://accord-framework.net/docs/html/T_Accord_MachineLearning_VectorMachines_Learning_LinearNewtonMethod_2.htm), ...) then they are restricted to a single thread.

Please note that is more advantageous to parallelize at a higher level than a lower level. If you are learning your machines as part of a grid-search or cross-validation routine, I would suggest to parallelize the learning of the several machines in the grid rather than the inner learning algorithm itself.

Hope it helps!

Best regards,
Cesar
