### ISSUE TITLE
Add codec H264 to Accord.Video.FFMPEG.VideoCodec

### ISSUE THREAD

**Issue by DenisTsapelnikov** [accord-net/framework#210]
May you add H264 codec to Accord.Video.FFMPEG?

**Comment by tpitman** [comment]
On top of that will there be any support for H265 (HEVC) and time soon? I know that the ffmpeg group recently announced support for it.

**Comment by cesarsouza** [comment]
Support for H.264, HUFFYUV, WebM and audio recording has been added on release 3.3.0.

**Comment by tpitman** [comment]
It doesn't crash anymore!!!!

I would like to know if I could get a good example of how to do a simple showing to the screen while recording, however, because my implementation doesn't work very well. After a few seconds of recording I get an out of memory error as well as the image on the screen and in the recorded file has weird artifacts. I have attached a sample file.

I have also added my .cs source code file. It is a C# WPF app. Just the main .cs file is relevant.

Please tell me what I am doing wrong.

This is on an i7 with NVidia 750M and 16GB of ram, so I don't think the computer is too slow for this.

I am just approaching this wrong I think.

In the .cs file you will see that I am setting FrameHolder in the xaml. Here is that component:

<Image x:Name="frameHolder" HorizontalAlignment="Stretch" Margin="0,25,0,0" VerticalAlignment="Stretch"/>

.cs file:
https://drive.google.com/open?id=0B3P6IntD-KkaQTNuMnd6Sm9lNkk

video file:
https://drive.google.com/open?id=0B3P6IntD-KkaMlBmR1QxMVliZms

**Comment by tpitman** [comment]
Thank you for the pointers to the examples. You are probably right. I will try out using your example and see what happens.

**Comment by Thenabadu** [comment]
Hi cesarsouza,

I used accord 3.3.0 (Accord.Video.FFMPEG.3.3.0). i try to decord, vp9 encoding webm file. but it is not success. (vp8 webm files we can) also cannot decode rtsp vp8 stream.( http vp8 stream can decord)

**Comment by aponcanos** [comment]
I want to get live video from RTSP of an IP Camera. Do you have any sample ?

**Comment by blaisexen** [comment]
hi @aponcanos 
this is from @cesarsouza at https://github.com/accord-net/framework/issues/905

Working with RTSP might be a bit more complicated than simply using an IP camera that supports the much simpler JPEG Stream protocol.

However, doing so is certainly not impossible. I think that the first step would be to get a library for RTSP in C# working, such as the one shown in this CodeProject's article entitled "Managed Media Aggregation using Rtsp and Rtp" (project available in CodePlex) or SharpRTSP. Then, it should be possible to write a new class in Accord.Video.FFMPEG that accepts a stream being received by one of those libraries and forward the received packets to FFMPEG so it could perform the actual video decoding.

> 
> If you would like, please open a new issue here in the issue tracker asking for this feature so we can track its progress!
> 
> Regards,
> Cesar

I hope that helps

**Comment by pratheekkpoojari** [comment]
Sir, videoFileWriter class needs Accord.Math.Rational class. But Rational just doesn't work.
is there any solution?
A example would be of great help.
