### ISSUE TITLE
Set Parameters of SequentialMinimalOptimizationRegression Class

### ISSUE THREAD

**Issue by mikesneider** [accord-net/framework#2152]
I am trying to set the parameters for the _SequentialMinimalOptimizationRegression_, For example, I need to set these parameters, but I have trouble with _gamma_, and _degree_.

```
{'C': 14008.699090460115,
 'degree': 1.5614840051214403,
 'gamma': 0.9313027879935729,
 'kernel': 'poly'}
```

I guess the parameter gamma is the same _Polynomial Constant_, is it?
and the degree must be an _int_, but I have a decimal number.
```
var learn = new SequentialMinimalOptimizationRegression<Polynomial>()
            {
                Kernel = new Polynomial(1.5614840051214403, 0.9313027879935729), // Polynomial Kernel of 2nd degree
                Complexity = 14008.699090460115 //same parameter C
            };
```

Help Topic: http://accord-framework.net/docs/html/T_Accord_MachineLearning_VectorMachines_Learning_SequentialMinimalOptimizationRegression.htm

**Comment by cesarsouza** [comment]
I am not sure if the gamma would correspond to the polynomial constant... Normally the constant is always set to either 0 or 1 to make the kernel be homogeneous or not. Rather, this looks to me like a [Composite Gaussian Kernel](http://accord-framework.net/docs/html/T_Accord_Statistics_Kernels_Gaussian_2.htm) which is basically a gaussian kernel taking as an input another kernel (in this case it could be the polynomial). 

Regarding the degree, hmm, I think the current implementation for the Polynomial kernel indeed expects an integer degree. It is not very complicated to provide your own kernel version which would accept a double degree though; you just have to create a class implementing the IKernel interface.

However, before doing that, I think it would be important to double check which kernel you actually need for the parameters you got. Do you have a reference paper?

**Comment by mikesneider** [comment]
Thank you @cesarsouza for your answer.
These parameters I got it from Sklearn model, that I ran it on Python.

**Comment by cesarsouza** [comment]
It is weird you got the polynomial degree as a floating point... If you check sklearn's documentation for SVR, degree is also an int there: https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVR.html#sklearn.svm.SVR

By the way, if you want to obtain comparable results to sklearn, you might want to use an algorithm that is equivalent to one of the algorithms that sklearn uses internally. If you are using SVR, I believe this should correspond to the [Fan-Chen-Lin's method](
http://accord-framework.net/docs/html/T_Accord_MachineLearning_VectorMachines_Learning_FanChenLinSupportVectorRegression.htm). There is an example on the wiki for it: https://github.com/accord-net/framework/wiki/Regression#support-vector-machines

In any case, please try to double-check what the gamma you got actually means, it has been a long time since I last took a look at libsvm and I am not completely sure to which parameter it would correspond right now.

**Comment by mikesneider** [comment]
Thank you @cesarsouza, one more question about the kernels. **Polynomial** is a kernel have the parameter gamma and parameter degree (which I agree it is an integer), but according to the next formula polynomial have a _gamma_ (<img src="https://render.githubusercontent.com/render/math?math=\gamma ">) coefficient, but in Accord I can not set this parameter, just _degree_ = _d_.

<img src="https://render.githubusercontent.com/render/math?math=k(x, y) = (\gamma x^\top y +c_0)^d">

**Comment by cesarsouza** [comment]
Yes I see, this is a scaled polynomial kernel. Well, I guess the simplest way to set the kernel as you would like is to create a class or struct implementing the IKernel interface. It can be something really simple, like this:

```csharp
public struct ScaledPolynomial : IKernel
{
    public double Gamma { get; set; }
    public int Degree { get; set; }
    public double Constant { get; set; }
 
    public double Function(double[] x, double[] y)
    {
        double sum = Constant;
        for (int i = 0; i < x.Length; i++)
            sum += x[i] * y[i];

       return Gamma * Math.Pow(sum, Degree);
    }
}
```

Then use it as your kernel. I haven't tested the above code, but hope it works!

**Comment by cesarsouza** [comment]
If the learning algorithm also expects some other interfaces to be implemented by the kernel, it is very likely you could just copy-paste them from the original Polynomial implementation here: https://github.com/accord-net/framework/blob/master/Sources/Accord.Statistics/Kernels/Polynomial.cs

**Comment by mikesneider** [comment]
thank you very much
