### ISSUE TITLE
Consider strategies to support computing bag-of-visual words in large datasets

### ISSUE THREAD

**Issue by cesarsouza** [accord-net/framework#30]
The current bag-of-visual-words impementation considers that images, resources, everything would be already in main memory. However, it should also be possible to create an alternate mechanism so images can be loaded from the disk in batches. A new clustering algorithm may also need to be implemented (such as an onine version of k-means).

https://groups.google.com/forum/#!topic/accord-net/AGeG___EWNg

**Comment by JakeTrans** [comment]
Hello, First off Thank you for building this framework, it has opened up Machine-Learning to me.  

I understand this is a old issue but in my use of the framework, I've modified the Learn method of BaseBagOFVisualWords5 in vision to accept a string array of file paths rather than the bitmap array. this in my limited testing seem to reduce the memory usage of the function by around 1GB.

`public TModel Learn(string[] x, double[] weights = null)

        {
            // Note: See note in the method below
            var descriptors = new TFeature[x.Length][];
            // For all images
            For(0, x.Length, (i, detector) =>
            {
                Bitmap ImageToLearn = (Bitmap)Bitmap.FromFile(x[i]);
                // Compute the feature points
                descriptors[i] = detector.ProcessImage(ImageToLearn).Select(p => p.Descriptor).ToArray();
                ImageToLearn.Dispose();
            });
            return Learn(descriptors.Concatenate());
        }`

Please let me know if this is of any use to you and if you would like me to submit this.

Thanks Again,

Jake

**Comment by cesarsouza** [comment]
The BagOfVisualWords class has been updated to include an [overload of the .Learn method that accepts an array of image filenames pointing to the image's locations on disk rather than the images themselves](http://accord-framework.net/docs/html/M_Accord_Imaging_BaseBagOfVisualWords_5_Learn_1.htm).

An example on how to use the feature has been added to the [main documentation page for the BagOfVisualWords class](http://accord-framework.net/docs/html/T_Accord_Imaging_BagOfVisualWords.htm).

Furthermore, it is now possible to consider subsamples of the training images and subsamples of descriptors from those training images as well. This can now be controlled by setting the [NumberOfDescriptors](http://accord-framework.net/docs/html/P_Accord_MachineLearning_BaseBagOfWords_6_NumberOfDescriptors.htm) and [MaxDescriptorsPerInstance](http://accord-framework.net/docs/html/P_Accord_MachineLearning_BaseBagOfWords_6_MaxDescriptorsPerInstance.htm) properties of the BagOfVisualWords class.
