### ISSUE TITLE
Distribution Analysis Question about Rank and Significance

### ISSUE THREAD

**Issue by Burkhardus** [accord-net/framework#312]
Hello Cesar,
I have a question regarding the Distribution Analysis. I added one Cauchy Distribution to the Distributions Collection. So all together I have 6 Distributions to test for.

![distanalysis](https://cloud.githubusercontent.com/assets/22381218/18900686/9da80468-8576-11e6-8017-b56f95650731.png)

I believe the result is calculated from the three different tests. If for example the KS-test and the CS-Test give the Gamma Disribution the rank 0, while the AD-test gives the Gamma-Distribution the rank 5 and Uni-Distribution the rank 0, the end result will be Gamma. But I found Gamma has the Significant-property set to true, although the PValue is below 0.05, in fact it is only 0.04xxx. Is there a reason for this?

**Comment by cesarsouza** [comment]
Hi Burkhardus,

Right now the DistributionAnalysis uses [only the chi-square goodness-of-fit test to compare distributions](https://github.com/accord-net/framework/blob/0928719940d6c9609a6882695d6292a7708c3783/Sources/Accord.Statistics/Analysis/DistributionAnalysis.cs#L563), even though it lists the results for all tests. The reason was simply because the chi-square is more general in the sense it can be applied to both continuous and discrete distributions, and is the simplest. The Kolmogorov-Smirnov and Anderson-Darling tests are restricted to continuous distributions, so their blind application may be problematic. 

Regarding the interpretation of the p-value, please note that it might be complicated to interpret it for the KS and AD tests, because it is not advisable to apply the KS test with the same data that has been used to fit the distribution. In this case, the distribution may still be used to provide a ranking like its the case in the DistributionAnalysis, but the critical values cannot be used to determine whether the test is significant or not. 

Those are some of the reasons why the chi-square test is the default test used to rank each of the distributions. However, in the end I should have made this a configurable option, as the best test may be dependent on each application. I will update the code to add this configuration option.

**Comment by Burkhardus** [comment]
If the significant is true, it means the test has passed or not? Because in the picture above you see in the Chi-Square test, the significant property is set to TRUE but the PValue is around 0.04.

**Comment by cesarsouza** [comment]
If the significant property is set to true, it would typically mean that the distribution of the samples differs from the distribution you are comparing against. In the context of the DistributionAnalysis, it would mean that the distribution was not a good fit. However, please note the tests in the analysis are not actually prepared to assert this. Rather, what the DistributionAnalysis class does is a simple ranking of candidate distributions based on those p-values, so the more likely ones come first. It cant be used to determine whether a sample _really_ came from each distribution, only tell you the most likely ones it might have came from, in likelihood order. 

In your case, may I ask if you are mostly interested on testing against the Gamma distribution? If so, this might require a different approach than just ranking candidates. If you know the parameters of the Gamma distribution that you are expecting, the best approach is to use the Kolmogorov-Smirnov test directly against this expected distribution (without fitting anything). However, if you do not know the parameters, then it will be necessary to use a Monte-Carlo approach to sample critical values of the Kolmogorov-Sminov test for the fitted distribution. I need to write an example on how this can be done, though.

Please let me know what problem you are trying to solve exactly, so we can see what would be the best approach!

Regards,
Cesar

**Comment by Burkhardus** [comment]
Hello César, thank you for your reply. What I'm trying to do is:

1. I have quality data measurements from a production process including lower and upper specification limit 

2. The requirement is to calculate the CPK (process capability index) to know the production process is stable and capable.

3. Show histogram and most mikely PDF function including average, max and min value, everything shown in the very first picture.

4. To achieve this I first have to test if my data is normal distributed. Only then I can really calculate a trustworthy CPK. Otherwise I have to use modified CPK calculation or accept that the CPK is not accurate. Then I want to color the bottom line result values red, otherwise I color them green.

Conclusion:

I think I have to use the distribution analysis to find the most likely distribution.

If the normal distribution is the most likely I have to check the PValue of the CS test. If the PValue is above 0.05 the normal distribution is not only the most likely but also meeting the criteria to be 95% most likely!

Then I calculate my CPK and color it green.

If the normal distribution is the most likely but the PValue is below 0.05 the j acclimate also the CPK but color it red.

Now I need to think about how many abs which kind of distributions I need to add to the distribution analysis.

And I need to check for modified CPK calculations fit unsymmetrical tailed distributions, like the gamma distribution.

I don't want to bake it too complicated, so maybe I skip the last point.

Sometimes I have mixed distributions. It would be perfect if I could analyze this and plot two distribution functions into the chart. But this is a very last nice to have.

**Comment by cesarsouza** [comment]
Hi Burkhardus,

Thanks for sharing those details! Actually some of them were quite important. An issue with statistical tests is that not all of them have the same power with different distributions. What this mean is that some tests perform better when comparing against certain distributions than others (i.e. while KS could be used to compare against any other distribution, if you know that you need to compare against a Gaussian distribution then maybe another, more specific test would be more appropriate).

If one of the first steps in your workflow is to check whether the data is Gaussian, please do so by using the [Shapiro-Wilk test first](https://en.wikipedia.org/wiki/Shapiro%E2%80%93Wilk_test#Power_analysis). If it is normal, then stop there and compute CPK; if it is not, then compute the modified CPK, and additionally try to rank the other distributions based on chi-square or KS (possibly using the Distribution Analysis) after excluding the Normal from the candidates. Since now you do not need to assert whether a distribution truly comes from a specific distribution to apply the modified CPK functions, you do not need a specific test anyways and maybe the chi-square would be quite appropriate as it is standard and easy to explain. 

You would only need the modified KS if you would like to show in the screen that the software is not able to recognize from which distribution it came from. If, however, you always display the more likely candidate, then you will not face this situation and you will not need the modified KS test.

I, in turn, learned that there are several things that might need to be added to the Distribution Analysis to make it more useful, which I will leave here as a TODO list that I can work upon:
 
TODO:
- Make distribution analysis smarter by applying more specific tests against specific distributions;
- Make the test used to sort the final decision of the analysis configurable;

**Comment by Burkhardus** [comment]
For the normal distributed samples the CPK calculation is defined

CPK = MIN [ (Mean - LSL) / (3*Sigma) , (USL - Mean) / (3*Sigma)) ]

Mean = Arithmetic Average Value
Sigma= Standard Deviation of the Normal Distribution
LSL, USL = Lower and Upper Specification Limit

Here in this web page are information about how to calculate the CPK for special conditions, like non normal distributed samples.

[http://m.qualitydigest.com/?url=http%3A%2F%2Fwww.qualitydigest.com%2Finside%2Fquality-insider-article%2Fproblems-process-capability-calculations.html&width=412](url)

The formula is been told like:

CPK = MIN [(Median - LSL) / (Median - p(0.00135)) , (USL - Median) / (p(0.99865) - Median) ] 

Media = Median
LSL, USL = Lower and Upper Specification Limit
p(x) = Percentil or a Normal Distribution with 3 Sigma limits, where x is between 0 and 100 % or 0 and 1. Depending on the Formula.

Now my question: Can I calculate the Percentiles with the Accord Framework. I found another Library on Codeproject called StatDescriptive which offers a Percentile function. But it seems, that the results are calculated on the basis of the sample values and not on a fittet distribution, so if the sample values are not symetric, the percentiles are not symetric, too. But according to the web site I have to calculate the percentiles on the basis of a normal distribution. Do the accord framework offers this function?

**Comment by cesarsouza** [comment]
Absolutely. You should be able to compute percentiles for most distributions using the [.GetRange()](http://accord-framework.net/docs/html/M_Accord_Statistics_Distributions_Univariate_UnivariateContinuousDistribution_GetRange.htm) method. Additionally, if eventually you also need a percentile based on the data itself, like the one described in the CodeProject article you mention, you can call .GetRange() from an [EmpiricalDistribution](http://accord-framework.net/docs/html/T_Accord_Statistics_Distributions_Univariate_EmpiricalDistribution.htm) fitted on your data.

Regards,
Cesar
