### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by mmehrle** [accord-net/framework#324]
I cloned the master branch but am getting build errors in VS2015. Here are a few:

Severity    Code    Description Project File    Line    Suppression State
Error       Metadata file 'C:\Users\xxxx\Documents\Accord-Net\Unit Tests\Debug\Accord.Math.dll' could not be found  Accord.Tests.MachineLearning    C:\Users\xxxx\Documents\Accord-Net\Unit Tests\Accord.Tests.MachineLearning\CSC  

Severity    Code    Description Project File    Line    Suppression State
Error   CS0246  The type or namespace name 'AccordTestsMathCpp2' could not be found (are you missing a using directive or an assembly reference?)   Accord.Tests.Math.Interop   C:\Users\xxxx\Documents\Accord-Net\Unit Tests\Accord.Tests.Math.Interop\BoundedBroydenFletcherGoldfarbShannoTest.cs 26  Active

Severity    Code    Description Project File    Line    Suppression State
Error   CS0246  The type or namespace name 'Info' could not be found (are you missing a using directive or an assembly reference?)  Accord.Tests.Math.Interop   C:\Users\xxxx\Documents\Accord-Net\Unit Tests\Accord.Tests.Math.Interop\LibBFGS\LBFGSComparer.cs    78  Active

Seems to me there is a problem with compiling the Accord.Math module.

**Comment by cesarsouza** [comment]
Hi there,

Thanks for opening the issue. It is very likely that the problem is not really with Accord.Math, but rather with the unit tests for Accord.Math. In order to compile the unit tests projects for Accord.Math, you need to have the previous VC++ toolchain installed in your system (also, you may want to build from the latest development branch).

Thus said, you can try disabling the Accord.Tests.Math.Interop and Accord.Tests.Math.Cpp unit test projects, or install the [VS2013 C++ platform toolset](https://www.microsoft.com/en-us/download/details.aspx?id=44914) that comes with any version of VS2013 (it was indicated in https://github.com/accord-net/framework#with-visual-studio-2015)

Please let me know if it helps solve the issue!

Regards,
Cesar

**Comment by mmehrle** [comment]
Confirmed. When I removed the unit tests for Accord.Math it compiled fine, yes. Thanks again for adding documentation for the random forest example. When can we expect this in the public NuGet package?

**Comment by cesarsouza** [comment]
Integrated in release 3.4.0.

**Comment by atika32** [comment]
The type or namespace name 'Accord' could not be found (are you missing a using directive or an assembly reference?) How i can resolve this error.
