### ISSUE TITLE
MulticlassSupportVectorMachine Save then Load and Learn some more

### ISSUE THREAD

**Issue by murphycrosby** [accord-net/framework#348]
Is it possible to save a MulticlassSupportVectorMachine after learning from a MulticlassSupportVectorLearning<ChiSquare>, then Load the MulticlassSupportVectorMachine back up and learn some more?

Or do you have to start the model from scratch and run all the items back through?

if it's possible to "append" learning, then how can I get back to the MulticlassSupportVectorLearning from the MulticlassSupportVectorMachine object?  I've tried saving the MulticlassSupportVectorLearning, but I get error when saving?

'Accord.MachineLearning.VectorMachines.Learning.MulticlassSupportVectorLearning`1[[Accord.Statistics.Kernels.ChiSquare, Accord.Statistics, Version=3.3.0.0, Culture=neutral, PublicKeyToken=fa1a88e29555ccf7]]' in Assembly 'Accord.MachineLearning, Version=3.3.0.0, Culture=neutral, PublicKeyToken=fa1a88e29555ccf7' is not marked as serializable.

Thanks!

**Comment by cesarsouza** [comment]
Hi Murphy,

At this time, the framework doesn't provide online learning algorithms for SVMs. This means that unfortunately machines have to be learned from scratch all the time. However, there is already an issue to track the addition of one of such algorithms: GH-231. They shouldn't be that much complicated to implement, but they still require some time.

**Comment by AhamedFasil** [comment]
Seen the results of your BoW sample applications in identifying the trained classes(Cats, Dolphins, Pandas, Sunflowers etc). I have used few faces and have seen it successfully classifying it. On going further, I wanted to save the learned network so that I can load it and use so as to avoid the time it takes for learning. Did save the generated feature vectors for all the images(double[][] inputs) used for training, its corresponding outputs( int[] outputs) and  serialized the MulticlassSupportVectorMachine(ksvm). 

But after loading, deserialising those save data and when I am trying to check the test images in  ksvm.Compute(freshly calculated feature vector for test image), the results are not coming correct, i.e the expected value and the actual value returned are different.
How can I sort this out, any hints, directions that you want share here, plz do.
Thanks!

**Comment by cesarsouza** [comment]
Hi @AhamedFasil, 

I am afraid I missed the update on this issue because it had already been closed a long time ago. If you are still facing this problem, please open a new issue here in the issue tracker and if possible, include a test project that reproduces the issue. 

Regards,
Cesar

**Comment by edgar-mtz-e** [comment]
Is it possible to see an example of how to serialise and deserialise a trained SVM?
