### ISSUE TITLE
I guess some wrong in example document

### ISSUE THREAD

**Issue by hzawary** [accord-net/framework#351]
Hi dear Dr,

In [WhitePatch class document](http://accord-framework.net/docs/html/T_Accord_Imaging_Filters_WhitePatch.htm) example, must be 'WhitePatch' instead of 'grayWorld' probably.
Not matter but, in last example of [MulticlassSupportVectorMachine class document](http://accord-framework.net/docs/html/T_Accord_MachineLearning_VectorMachines_MulticlassSupportVectorMachine.htm), i guess be 'calibration' instead of 'machine' and also a question: how can I use the other kernel types of `ProbabilisticOutputCalibration<TKernel>` class in programatically? cause has not any property like 'Kernel' to set a kernel.

regards,
HZ

**Comment by cesarsouza** [comment]
Hi HZawary!

Many thanks for reporting those issues! Regarding the ProbabilisticOutputCalibration, it shouldn't be necessary to set a Kernel function on it because it is supposed to take the function from the already learned machine that it is going to calibrate. In this case, it is not necessary to set a kernel function again.

Regards,
Cesar

**Comment by cesarsouza** [comment]
The examples have been updated!
