### ISSUE TITLE
Issue in NaiveBayesLearning code

### ISSUE THREAD

**Issue by bala4sight** [accord-net/framework#354]
The attached project crashes when training  naïveBayse . I request provide  a solution for this issue .4
[AccordConsole.zip](https://github.com/accord-net/framework/files/633130/AccordConsole.zip)

**Comment by cesarsouza** [comment]
Hi there,

The problem is happening because the example learning problem that is being used to train/exercise the NaiveBayes wrapper has only one sample. With a single sample, it is impossible to compute a Variance (which is then left at zero), and thus the program fails. 

It is possible to circumvent the issue by adding a small constant to the estimation of all variances, as a regularization term. To do that you can use:

```
          var learner = new NaiveBayesLearning<NormalDistribution>();
          learner.Options.InnerOption = new NormalOptions()
          {
              Regularization = 1e-12
          };
```

Regards,
Cesar
