### ISSUE TITLE
Error on EigenvalueDecomposition .ctor ambigous

### ISSUE THREAD

**Issue by ebortoluzzi** [accord-net/framework#359]
Hi I'using your library Accord.math 3.3.0 with VS2008 VB.net, mainly for SVD and matrix, so far everything was working fine, but when I tried an EigenvalueDecomposition I got an error
Dim Eiv As New EigenvalueDecomposition(M)     ' M(2,2)

but got and error that says .ctor is ambigous, many types exist with same name in Accord.math class:

Errore	1	'.ctor' è ambiguo perché esistono diversi tipi di membri con lo stesso nome in class 'Accord.Math.Decompositions.EigenvalueDecomposition'.

**Comment by cesarsouza** [comment]
Hi there,

Thanks for using the library! It seems that what the message is actually saying is that there are many members with the same name in the class definition. This is because the EigenvalueDecomposition has many constructor overloads, including some that include optional parameters. One possible solution to this problem is to use named parameters, as in:
```
Dim Eiv As New EigenvalueDecomposition(matrix:=M, assumeSymmetric:=false, inPlace:=false)
```

I am not very experienced with VB.NET, so I am not quite sure if the syntax I used above is entirely correct. But the use of named parameters should be sufficient to resolve the constructor ambiguities.

I will also try to remove this ambiguity in the next release. Thanks for reporting the issue!

Regards,
Cesar

**Comment by ebortoluzzi** [comment]
Hi, I tried your sintax but still got an error on the Eiv by the VS2008 IDE telling me that the usual
Errore	1	'.ctor' è ambiguo perché esistono diversi tipi di membri con lo stesso nome in class 'Accord.Math.Decompositions.EigenvalueDecomposition'.	E:\EB\Visual Studio 2005\Libraries\NumericalRecipesVB\NumericalRecipesVB\NRvb.vb	1050	7	NumericalRecipesVB

**Comment by cesarsouza** [comment]
Just an update to this issue. 

It seems the following code seems to work fine in VB.NET in VS 2017:

```vb.net
Dim M = Matrix.Random(2, 2)
Dim Eiv As New EigenvalueDecomposition(M) ' M(2,2)
```

Regards,
Cesar
