### ISSUE TITLE
 KNearestNeighbors parallel

### ISSUE THREAD

**Issue by datashinobi** [accord-net/framework#401]
Is  KNearestNeighbors parallel?

Can it take a custom distance function and run in multi threads

**Comment by cesarsouza** [comment]
Hello there,

The [current implementation of the k-Nearest Neighbors can be found here](https://github.com/accord-net/framework/blob/development/Sources/Accord.MachineLearning/KNearestNeighbors%601.cs). Unfortunately, as it can be seen, it does not use multiple threads (yet). 

However, it should be fairly straightforward to replace the standard loops in the algorithm by Parallel.For calls. I can update it in some days. But since it might be simple to implement it, please also feel free to send a pull request or ask more information on how to do it!

Regards,
Cesar

**Comment by cesarsouza** [comment]
Fixed in 3.5.0.
