### ISSUE TITLE
LevenbergMarquardtLearning serialization error in v3.4.0

### ISSUE THREAD

**Issue by greeb36** [accord-net/framework#410]
When trying to serialize a member of class LevenbergMarquardtLearning in Accord.Neuro.Learning version 3.4.0, I receive the error:

Exception thrown: 'System.Runtime.Serialization.SerializationException' in mscorlib.dll

Additional information: Type 'Accord.Neuro.Learning.LevenbergMarquardtLearning' in Assembly 'Accord.Neuro, Version=3.4.0.0, Culture=neutral, PublicKeyToken=fa1a88e29555ccf7' is not marked as serializable.

I believe this may also be a problem for other classes deriving from ISupervisedLearning in the same library.

**Comment by cesarsouza** [comment]
Hello there,

Many thanks for opening the issue!

Indeed, most of the learning algorithms are not marked as Serializable. Normally, only the underlying model is serializable, but not the learning algorithm. For example, in the case of neural networks, the ActivationNetwork object that is being trained is serializable, but the LevenbergMarquardtLearning algorithm isn't. 

This is the default behavior because most of the time the learning algorithms can not be paused and resumed later. However, it is true that Levenberg-Marquardt could indeed make use of this feature. In this case, can you please let me know of the particular use case you have in mind where serializing the learning algorithm would make sense? I might come up with a better implementation tailed for the case you need, or at least some unit tests to reflect better your intended usage.

Best regards,
Cesar

**Comment by cesarsouza** [comment]
The Neuro namespace should be replaced by Keras Sharp in the future. I am therefore closing this issue for now.
