### ISSUE TITLE
Small bug in SMO algorithm

### ISSUE THREAD

**Issue by ignaciotb** [accord-net/framework#487]
Hi Cesar, 

First of all, thanks for your nice work with this framework, it's being very useful to take a first look at SVMs to me. Although I think there's a mistake in your SequentialMinimalOptimization.cs. I believe the new values for the clipped multipliers H and L should be inverted in lines 1001 and 1002, according to the original literature. 

Regards

**Comment by blaisexen** [comment]
listening...

**Comment by cesarsouza** [comment]
Hi there,

Sorry for the extremely long delay in answering this message. However, I am almost sure this is not a bug - when I implemented the SMO algorithm, I remember that actually some of the definitions I have used had swapped signs in relation to the literature. Otherwise, the machines would not have learned anything in many standard problems.

If you think this is indeed an issue, please try to invert the definition of L and H and check whether the unit tests still pass, or whether you can get improved performance on standard tasks such as MNIST classification. If anybody can confirm that indeed performance is better, please re-open this issue and I will take a look at it again.

Regards (and thanks very much for opening the issue),
Cesar
