### ISSUE TITLE
Download is a scrap  scrap  scrap  scrap  scrap  scrap  scrap  scrap  scrap  scrap  scrap  scrap  scrap  scrap  scrap  scrap  scrap  scrap  scrap  scrap 

### ISSUE THREAD

**Issue by clementmarcotte** [accord-net/framework#502]
It is nearly 30 times I tried downloading Accord-net framework. Eeach time GIthub or their friends close connection when download it about 20 % completed et there's no way to recover. Each time, it was start from scratch, each time connection failed.

If you don't want your software being downloaded, just erase download links and shut business down.

Clément Marcotte (ANGRY)

**Comment by cesarsouza** [comment]
Hello Clement,

First of all, sorry for the delay in answering your message. The past days have been quite crazy due the camera-ready deadline for a conference (the most important conference I've ever submitted to, so I hope you will understand). While I understand your frustration, unfortunately there is not much I can do about the quality of GitHub's file distribution servers. However, what one thing that might surely help you (in case you are still having problems downloading the framework) is to download it through NuGet rather than using GitHub. This way, you will be able to download only the parts of the framework that you will actually need/use in your application, and thus drastically reduces the chances of something going wrong.

Hope it helps.

Regards,
Cesar

**Comment by cesarsouza** [comment]
Here is a guide you can use to download the framework using NuGet: https://github.com/accord-net/framework/wiki/Getting-started

In summary, just right-click your project's name in Visual Studio's Solution Browser window, then click "Manage NuGet packages." In the window that opens, search for Accord.NET and select the binaries you would like to use in your project, then click "install".

Regards,
Cesar
