### ISSUE TITLE
Exception in WriteVideoFrames

### ISSUE THREAD

**Issue by AlexGimo** [accord-net/framework#588]
Hello,
I was using visual studio 2017, compiling my solution with x86 architecture, and using WriteVideoFrame I got these messages:
[libx264 @ 10960B20] non-strictly-monotonic PTS
[libx264 @ 07B8EB40] non-strictly-monotonic PTS
The behavior is periodic (one every sec more or less) and the CPU usage drops to 0 for some millisecond together with this message.
My colleague tried to compile too the solution with visual studio 2013 and the programs worked fine (even if I run the .exe on my PC). Thus I thought it was a compiler problem, but now I have installed visual studio 2013 (the same of my colleague) but compiling the project the message shows up again.
Any idea?
Thanks,
Alex

**Comment by cesarsouza** [comment]
Hi there,

This should likely have been fixed in the current development release. Indeed, there was a problem with the way the time point of each frame was being informed to the encoder.

Regards,
Cesar

**Comment by AlexGimo** [comment]
Actually even in the new version (3.5.0) I continue to have this exception (just only with H264 codec).
Thanks,
Alex

**Comment by cesarsouza** [comment]
Hi there,

Sorry, when I meant it was fixed in the current development branch I didn't mean to imply it had been included in the latest official release. In fact, it has just been included in the latest pre-release versions 3.5.1-alpha and 3.5.2-alpha, released yesterday and today, respectively (I forgot to include some a fix in yesterday's release and had to generate a new one today, that's why those two small releases in quick succession).

Can you please try with the latest pre-release version (3.5.2-alpha) to see if you still experience the same issue?

Regards,
Cesar

**Comment by cesarsouza** [comment]
Added in release 3.6.0.
