### ISSUE TITLE
MultilabelSupportVectorLearning  decide gives bool[][] with all false values

### ISSUE THREAD

**Issue by Manimojy** [accord-net/framework#608]
Multilabelsupportvectorlearning Decide method returns false values. Here is my code:
     
        MultilabelSupportVectorMachine<Linear> machine0;
       
        private void button4_Click(object sender, EventArgs e)
        {
            MultilabelSupportVectorLearning<Linear> msvl = new MultilabelSupportVectorLearning<Linear>()
            {                
                Learner = (param) => new SequentialMinimalOptimization<Linear>()             
                {   
                }
            };
            msvl.ParallelOptions.MaxDegreeOfParallelism = 1;
            machine0 = msvl.Learn(data16.ToArray(), labels.ToArray());
        }

I have attached the data and label files.
[data16.txt](https://github.com/accord-net/framework/files/1017167/data16.txt)
[labels16.txt](https://github.com/accord-net/framework/files/1017168/labels16.txt)

**Comment by Manimojy** [comment]
Also, I will open a new issue regarding the speed performance of both MultiLabelSupportVectorMachine and MulticlasssupportvectorMachine.

**Comment by cesarsouza** [comment]
So, the problem is that it outputs false values, or that it outputs only false values? 

If the problem is that it outputs false values instead of integer labels, it is because it has to be converted to a Multiclass() classifier first. If I am not mistaken, cast machine0 to a multi-class classifier using 
```
var svm = machine0.ToMulticlass();
```
and then you will be able to get integer class labels as output.

However, if the problem is that, in this particular problem, the machine is giving _only_ false values, then the problem is either that the data has too many contradictions or the complexity parameter C is not high enough. For instance, you can try using a more specialized learning algorithm for the linear kernel, with a higher C to force it to overfit to your data:

```
var msvl = new MultilabelSupportVectorLearning<Linear>()
{
    Learner = (param) => new LinearDualCoordinateDescent<Linear>()
    {
        Complexity = 10000000,
    }
};

var svm = msvl.Learn(x, y);

var pred = svm.Decide(x);
```

You will see that this time, some labels are different from false. If this is the case, then you might need to try different values for C while testing on a separate set of values to have a better idea on which value to use.

Hope it helps!

Regards,
Cesar

**Comment by Manimojy** [comment]
My machine0 is a MultilabelSupportVectorMachine  and I don't find any ToMultiClass() method. Also the Help file for MultilabelSupportVectorMachine says:
Note: This API is now obsolete. (I'm using version 3.4.0)
Also, please add underneath the Note the new API that we need to refer to.

Adding Complexity with different values didn't help. most of the results by Decide method were not accurate  and the computation was very slow (~5 seconds).

**Comment by cesarsouza** [comment]
Are you using NuGet? Can you try updating to 3.5?

**Comment by cesarsouza** [comment]
Also, if you decide to update, please remember to make a backup copy of your project before you install the new version.

**Comment by Manimojy** [comment]
No NuGet. I downloaded from https://github.com/accord-net/framework/releases. 
Downloading 3.5 :)
Sure.. I'll backup. :)

**Comment by cesarsouza** [comment]
Hello there,

Are you still experiencing the problem? Please feel free to reopen the issue in case upgrading to the latest release didn't help.

Regards,
Cesar

**Comment by Manimojy** [comment]
sorry for late reply (house shifting, new internet connection).. 
So far no problem after upgrading to the latest release.. :)

**Comment by cesarsouza** [comment]
Amazing! Thanks for letting me know, and I hope the framework can be useful to your needs! 👍
