### ISSUE TITLE
MultiLabelSupportVectorMachine and MultiClassSupportVectorMachine slow performance

### ISSUE THREAD

**Issue by Manimojy** [accord-net/framework#609]
Testing MulticlasssupportVectorMachine with SequentialMinimalOptimization with 70000 samples took 76 seconds with 65% CPU usage. 
Testing MulticlasssupportVectorMachine with LinearDualCoordinateDescent with 70000 samples took 136 ms with 1.1% CPU usage. 
My code which gives ALMOST the same result took 52 ms and 0.4% cpu. 
Why are these differences?

Below is my code to find the labels:

            int[] l1 = new int[ed - st];
            for (int i = st; i < ed; i++)
            {
                double[] s = new double[totalClusters];
                for (int j = 0; j < centris.Length; j++)
                {
                    s[j] = simi.GetSimilarityScore(centris[j], dpts[i]);
                }
                l1[i - st] = s.IndexOf(s.Max());
             }
I clustered my 100000 training data, each data =double[] of 9 elements, into 16 clusters. And in the above code I compare (using EuclidieanSimilarity)  each TEST data with all the 16 centroids and I select the max similar value.

The data16 file contains only few samples that are closer to each centroid. 
[data16.txt](https://github.com/accord-net/framework/files/1017196/data16.txt)
[labels16.txt](https://github.com/accord-net/framework/files/1017197/labels16.txt)

.

**Comment by cesarsouza** [comment]
Hi there,

Thanks for opening the issue and interesting questions!

I can give a few comments which I hope might explain the performance you see. First of all, the the Linear* learning algorithms are specialized algorithms that can only be used with Linear SVMs. Since they do not have to worry about the most general case where the kernel is non-linear, they can implement code that is most efficient for the particular case of linear kernels. 

On the other hand, Sequential Minimal Optimization has to deal with the general case, where kernels can be non-linear. Also, note that while SMO was one of the first successful learning algorithms for SVMs, many other, improved algorithms, came after it. If you want to try, since version 3.5 (released today), there is a new mode for SMO that might finish training faster. You can use it by specifying SelectionStrategy.SecondOrder as its [Strategy property](http://accord-framework.net/docs/html/P_Accord_MachineLearning_VectorMachines_Learning_BaseSequentialMinimalOptimization_3_Strategy.htm).

Furthermore, please bear in mind that both multi-class and multi-label SVM algorithms are actually based on training a set of binary SVM algorithms after each class (or class pair) in your multi-class decision problem. This means that the problem does not scale very well as the number of classes increase. If you have 128 classes in a multi-class setting the MulticlassSupportVectorMachine object needs to create and train around 8k smaller SVMs. Multilabel needs to create and train a smaller number of 128 SVMs, but their learning problems are significantly larger than in the multi-class case.

Now, regarding the example you posted, while it can be used for classification, I don't think it would qualify exactly as an algorithm for SVMs. An SVM algorithm tries to arrive at an optimal discriminative solution for the classification problem. In the way that I understand your example, you are creating a generative classifier which does not need to discriminate at all between the different features in your dataset. I think it would be more comparable to the [MinimumMeanDistanceClassifier](http://accord-framework.net/docs/html/T_Accord_MachineLearning_MinimumMeanDistanceClassifier.htm) with a custom distance function instead. Because you do not have to solve one optimization problem for each different class in your dataset, it is somewhat expected that generative algorithms like those can train much faster. However, their result will not have any optimality guarantees.

Hope it helps!

Regards,
Cesar
