### ISSUE TITLE
FFmpeg VideoFileWriter bug with Rational FrameRate.

### ISSUE THREAD

**Issue by raheelasadkhan** [accord-net/framework#611]
There is a bug when writing a video file as follows:

```
	var fileInput = new FileInfo(@"Input.mp4");
	var fileOutput = new FileInfo(@"Output.mp4");

	using (var videoFileReader = new Accord.Video.FFMPEG.VideoFileReader())
	{
		videoFileReader.Open(fileInput.FullName);

		using (var videoFileWriter = new Accord.Video.FFMPEG.VideoFileWriter())
		{
			videoFileWriter.Open
			(
				fileOutput.FullName,
				videoFileReader.Width,
				videoFileReader.Height,
				// Shows correctly: 30 (Numerator: 30, Denominator: 1).
				videoFileReader.FrameRate,
				Accord.Video.FFMPEG.VideoCodec.H264
			);

			do
			{
				using (var bitmap = videoFileReader.ReadVideoFrame())
				{
					if (bitmap == null) { break; }
					videoFileWriter.WriteVideoFrame(bitmap);
				}
			}
			while (true);

			videoFileWriter.Close();
		}

		videoFileReader.Close();
	}

	using (var videoFileReader = new Accord.Video.FFMPEG.VideoFileReader())
	{
		videoFileReader.Open(fileOutput.FullName);

		// Shows incorrectly: 15360 (Numerator: 15360, Denominator: 1).
		var frameRate = videoFileReader.FrameRate;
	}

```

**Comment by cesarsouza** [comment]
Hi there,

Many thanks for opening the issue! It seems FFMpeg is changing the time_base parameter of the video stream after a call to avformat_write_header. It seems to be exactly the same issue described in this Stackoverflow question: https://stackoverflow.com/questions/29850246/ffmpeg-avformat-write-header-changing-my-stream-time-base

I am investigating what the proper fix would be, but any suggestions are also welcome.

**Comment by raheelasadkhan** [comment]
Hey there,

Thanks. I see that this issue has nothing to do with the Rational type. Sadly, I'm only able to use the Accord managed library so will have to revert back to an earlier version for now.

Just in case it is related, using the 'videoFileWriter.WriteVideoFrame(bitmap, timeStamp)' overload throws the exception: 'Error while writing video frame. HResult: -2146233088'. This happens with any container/codec combination I try without fail after a few frames have been added successfully (usually < 30). I wonder if this is happening because a frame rate has been explicitly specified.

Happy investigating. :)

**Comment by cesarsouza** [comment]
Also: https://stackoverflow.com/questions/13565062/fps-too-high-when-saving-video-in-mp4-container

**Comment by cesarsouza** [comment]
Hi there,

Indeed, the second issue you reported was related. The overall issue started happening after the FFmpeg library used by the framework had been updated to a recent version, after being stuck with a version from 2012 for about 5 years. 

Differently from before, it seems that now FFmpeg is free to change the video stream's time_base to something else after the stream has been initialized (header has been written), and now it's necessary to convert timestamps to the new base just before the packet is written to disk (i.e. before libffmpeg::av_interleaved_write_frame). 

This issue was not immediately visible because the current code was working fine for containers that expected a constant frame rate (i.e. ".avi") if frames were written in order and without custom time stamps. However, it would fail in case we were saving into containers that allowed for variable frame rates (i.e. ".webm", ".mp4", ".ogv").

The fixes will be committed soon.

Regards,
Cesar

**Comment by raheelasadkhan** [comment]
Hi Cesar,

Any chance this fix will be pushed as an updated NuGet package?

Thanks,

Raheel.

**Comment by cesarsouza** [comment]
Hi @raheelasadkhan,

The fix is already available in the pre-release versions of the Accord.NET packages in NuGet. Please let me know if they do not work for you.

Regards,
Cesar

**Comment by raheelasadkhan** [comment]
Hi @cesarsouza,

Thank you. It works flawlessly.

I will however, have to wait for a production release in order to use it in my core project. Since I'm new to open-source, not too sure how this works and whether you are the authority on production releases. If you do have a planned date, please do let me know.

Thank you very much again for this fix and please feel free to reach out if I can contribute in any way.

Regards,

Raheel Khan

**Comment by cesarsouza** [comment]
Fixed in release 3.6.0.

**Comment by lioz** [comment]
Hi @cesarsouza,
Thanks for your work.
I have the same problem. I use Accord.Video.FFMPEG.x64 3.6.0, Accord.Video 3.6.0 and Accord 3.6.0. I include ffmpeg-3.2.2-win64-shared to output folder. I use .NET 3.6.1.
If i don't use TimeSpan on WriteVideoFrame, i don't have problem.

Do you have any idea that what happen?
Thanks

**Comment by cesarsouza** [comment]
Hi @lioz,

Hmmm... Can you try to make sure that all your TimeSpans are unique? Please try registering all the different timespans that you are passing to the WriteVideoFrame method, and please check if the difference between two consecultive timespans are not less than the frame rate.

If the difference between consecutive timespans is higher than the framerate and you are still getting this problem, please let me know.

Regards,
Cesar

**Comment by lioz** [comment]
@cesarsouza , thanks for your quick response.
I registered times in miliseconds. I defined FPS = 30 and worked until time 652.96 but when i tried save frame on 685,48, i have error "Error while writing video frame".

The times of frames are: 

Information | 1:40:26 p. m. | 0
Information | 1:40:27 p. m. | 46.0318
Information | 1:40:27 p. m. | 61.5439
Information | 1:40:27 p. m. | 101.0755
Information | 1:40:27 p. m. | 145.1025
Information | 1:40:27 p. m. | 159.6135
Information | 1:40:27 p. m. | 186.1321
Information | 1:40:27 p. m. | 244.6743
Information | 1:40:28 p. m. | 259.685
Information | 1:40:28 p. m. | 289.7049
Information | 1:40:28 p. m. | 331.7347
Information | 1:40:28 p. m. | 384.7733
Information | 1:40:28 p. m. | 384.7733
Information | 1:40:28 p. m. | 426.302
Information | 1:40:29 p. m. | 481.3416
Information | 1:40:29 p. m. | 495.8516
Information | 1:40:29 p. m. | 523.872
Information | 1:40:29 p. m. | 582.4128
Information | 1:40:29 p. m. | 598.4242
Information | 1:40:30 p. m. | 636.9531
Information | 1:40:30 p. m. | 652.9636
Error | 1:40:30 p. m. | 685.4864

**Comment by lioz** [comment]
Hey @raheelasadkhan, how are you? Can you said me if this problem is fixed for you? What version you are using? I have the same problem and dont understand whats happen :/

**Comment by jfrank14** [comment]
@cesarsouza: are you saying that one must not write a video frame unless one frame rate interval has passed since the previous frame? I having been battling this issue for a few days and I'm still blowing up almost immediately if I specify a timestamp, but it works fine if I don't. I've got a frame rate of 30 and see logs like the one below. You can see that the difference between each write is right around 30ms, but there is one that's a little less and then it crashes, but the crash is a number of frames later:

>Timestamp 00:00:00.6622259|00:00:00.0348772
Timestamp 00:00:00.6911483|00:00:00.0289224  <--- note less than frame rate of 30
Timestamp 00:00:00.7231071|00:00:00.0319588
Timestamp 00:00:00.7549772|00:00:00.0318701
Timestamp 00:00:00.7879034|00:00:00.0329262
Timestamp 00:00:00.8347635|00:00:00.0468601
Timestamp 00:00:00.8676757|00:00:00.0329122
Timestamp 00:00:00.8995909|00:00:00.0319152
Exception thrown: 'Accord.Video.VideoException' in Accord.Video.FFMPEG.dll
An exception of type 'Accord.Video.VideoException' occurred in Accord.Video.FFMPEG.dll but was not handled in user code

**Comment by prajithcs23** [comment]
@jfrank14, Are you found any solution to this issue?
I am also facing the same.
I am using the Accord version 3.8.0
The error stack is as follows,
 at Accord.Video.FFMPEG.write_video_frame(WriterPrivateData data)
   at Accord.Video.FFMPEG.VideoFileWriter.WriteVideoFrame(BitmapData frame, UInt32 frameIndex)
   at Accord.Video.FFMPEG.VideoFileWriter.WriteVideoFrame(Bitmap frame, UInt32 frameIndex)
   at Accord.Video.FFMPEG.VideoFileWriter.WriteVideoFrame(Bitmap frame, TimeSpan timestamp)

Error Message: Error while writing video frame.


Source: Accord.Video.FFMPEG

If I write the video without Time-span, then while playing the saved video behaves like as fast-forwading!

@cesarsouza, please guide me..

**Comment by jingdaradal** [comment]
While waiting for the fix. 
I temporary put a Thread.Sleep(100) before append the next bitmap

`Thread.Sleep(100);
var now_ticks = DateTime.Now.Ticks;
var ff_ticks = _firstFrameTime.Value.Ticks;
var ticks = now_ticks - ff_ticks;

_videowriter.WriteVideoFrame(bitmap, new TimeSpan(ticks));`

just a work around
