### ISSUE TITLE
Can't create mp4 file with different extension

### ISSUE THREAD

**Issue by TharosTheDragon** [accord-net/framework#620]
I'm not sure how VideoFileWriter works internally. Does it actually look at the extension of the file name in order to figure out what container format to use? Does this mean you have to end a file name with .mp4 in order for it to work as an mp4 file? What if I want to create an unofficial file extension? The file won't play even when I manually change the extension to .mp4. Is it not getting written correctly?

**Comment by cesarsouza** [comment]
This is actually done internally by FFmpeg. It can guess the file format to be used depending on many hints, one of them being the file name.

If you would like to create an unofficial file extension, I would recommend renaming the file afterwards. Otherwise, it would be necessary to look up on FFmpeg APIs how to ignore the filename and force a particular container when encoding.

Regards,
Cesar

**Comment by TharosTheDragon** [comment]
Thanks for the reply, Cesar! I actually already figured this one out. Sorry, I guess you didn't get my email. I made a new VideoFileWriter method that takes both an argument for the actual file name and another for the filename that should be used for guessing the container format.

**Comment by cesarsouza** [comment]
Yep, sorry for the delay in answering! Sometimes I don't get GitHub notifications.
