### ISSUE TITLE
Inject other Random.Generator (like mersenne twister)

### ISSUE THREAD

**Issue by nwiman** [accord-net/framework#628]
For now you can only control the seed of the Accord.Math.Random.Generator, but i want to change the Generator to a MersenneTwister... is there a reason for having the Generator readonly, if you could inject a generator and know the limitations wouldn't this be a good thing?

**Comment by cesarsouza** [comment]
Hi there,

Well, the reason for having it read-only is that changing this generator might affect the behavior of the entire framework, and not only the code that you need.

However, I agree that the framework shouldn't prevent much what users can do with it, so probably this could be changed.

May I ask which components/classes are you mostly interested in using with a different generator?

**Comment by nwiman** [comment]
Yes, I understand that this is a central piece but I think the implementation is a bit problematic as it (as you say) prevent one from changing the random generator.

The class for now that I want to use a Mersenne twister generator in is the MultivariateNormalDistribution.
It would be nice to have a container that you could bootstrap with a generator or an override where you pass a System.Random, I haven't looked too much in the source code but you maybe have an idea of how to do this in a clean way...

Thanks for a great lib and a quick reply (as always :)) 

Cheers

**Comment by fsteveb** [comment]
It looks like the random class in the framework needs a factory pattern
where the type of generator can be selected. I would be willing to add
several generators to the library if that is a desired feature.
Steve

**Comment by nwiman** [comment]
Yes I see what you mean, but in my case I need to get hold of the actual reference to the Random as well.
As I need to continue to get my random numbers in sequence after my call to Generate my samples from the Accord.Net MultivariateNormalDistribution, if you see where I am getting at?

**Comment by cesarsouza** [comment]
@fsteveb Thanks a lot for the comment and offer to help! The framework currently offers an ```IRandomNumberGenerator<T>``` interface that can be used in the implementation of random generators. Currently there are already some generators specified there, such as the [Uniform Ziggurat](http://accord-framework.net/docs/html/T_Accord_Math_Random_ZigguratUniformOneGenerator.htm) but the list is not extensive right now. It would be nice to have new ones, if someone would be willing to contribute some new implementations :-) 

However, I still think that replacing the central generator is not a very good idea as it can be quite hard to control it since it can be called from anywhere in and outside the framework, including multiple threads.

@nwiman I had the suspicion you would like to use it from inside the probability distributions :-) In this case, what maybe could easily be done without breaking too much code is to add a new property or virtual method to the base class of all distributions where a ```IRandomNumberGenerator<T>``` could be specified. Then the probability distributions could be changed to take the generator from this property/method instead of ```Accord.Math.Random.Generator.Random```.

**Comment by nwiman** [comment]
I like the Idea of the interface option, it seems simple for a starter... :)

**Comment by nwiman** [comment]
For now I'm only using the Generate function but I suspected that you would have to pass the "random" in the ctor or the generate function as it in the MultivariateNormal case uses a static Random function on the NormalDistribution. 
The MersenneTwister is inherited from .NETs Random so this will hopefully work like a charm...

Thanks again for all support!

**Comment by cesarsouza** [comment]
Added in release 3.6.0.
