### ISSUE TITLE
Multilabel SVM - Different outputs with same SMO learning parameters

### ISSUE THREAD

**Issue by mhusinsky** [accord-net/framework#63]
Hi Cesar,

I just noticed something weird when training Multilabel SVMs and am not sure if there is a bug involved here. When taking the example code from the documentation to setup the machines

    teacher.Algorithm = (svm, classInputs, classOutputs, i, j) =>
        new SequentialMinimalOptimization(svm, classInputs, classOutputs);

for the given examples of [0,3,1,2]  i get the following output:

     -1 1 -1
     -1 -1 -1
     -1 1 -1
     -1 -1 -1

When configuring the training algorithm like this (setting the values of complexity, epsilon and tolerance to the same values is just for making the point):

            teacher.Algorithm = (svm, classInputs, classOutputs, a, b) =>
               {
                   var smo = new SequentialMinimalOptimization(svm, classInputs, classOutputs);
                   smo.Complexity = smo.Complexity;
                   smo.Epsilon = smo.Epsilon;
                   smo.Tolerance = smo.Tolerance;
                   return smo;
               };

the output is now:

    -1 1 -1
    -1 -1 1
    -1 1 -1
    -1 -1 -1

(notice the different value in the second row, third value)
even though the configure parameters for the learning algorithm should not have been changed, the output of the machine is different. 
is this intended behaviour?

thank you for your great work!

**Comment by cesarsouza** [comment]
Hi mhusinsky!

If you are using the latest alpha version from NuGet (or the latest version in the development branch), this happens because of the line

    smo.Complexity = smo.Complexity

The point is that, if you don't set a complexity parameter directly, the SMO algorithm will try to guess an initial Complexity value automatically from the data. But when you set any value for the complexity manually, it will not attempt to estimate it from the data but will rather use the value you passed to it.

If you would like to keep the same behavior, pass also the value of the property [smo.UseComplexityHeuristic ](http://accord-framework.net/docs/html/P_Accord_MachineLearning_VectorMachines_Learning_BaseSupportVectorLearning_UseComplexityHeuristic.htm), as in

        teacher.Algorithm = (svm, classInputs, classOutputs, a, b) =>
        {
               var smo = new SequentialMinimalOptimization(svm, classInputs, classOutputs);
               smo.UseComplexityHeuristic = smo.UseComplexityHeuristic;
               smo.Complexity = smo.Complexity;
               smo.Epsilon = smo.Epsilon;
               smo.Tolerance = smo.Tolerance;
               return smo;
         };

Please let me know if this solves the issue!

Best regards,
Cesar

**Comment by mhusinsky** [comment]
hi cesar,
thanks for your quick response and clearing that up.
indeed i use 2.14.3 alpha from NuGet but use the current version online documentation, where this behaviour is not mentioned (or at least i did not spot it).
anyway, now everything behaves as expected. issue solved - thanks again!

all the best,
matthias
