### ISSUE TITLE
Bad quality of videos with H264 codec 

### ISSUE THREAD

**Issue by AlexGimo** [accord-net/framework#633]
Hi,
I was recording a video with H264 codec and it was quite good (version 3.4.2-alpha). Last week I updated the accord.video.ffmpeg library to 3.5.0 and now the quality is terrible.  Do I have to change something?

Plus. I cannot go back to v3.4.2-alpha since nuget says can't resolve dependency with Accord.Core.

Note. I updated the library (new version is fine) since I noted a difference in the pixel value written from the VideoFileWriter from the real value (i needed precise values since it was a depth video)

**Comment by cesarsouza** [comment]
Hi there,

Indeed there were some changes regarding FFMPEG in the weeks during the two releases. However, in order to understand better what happened, can you please clarify: you mentioned that you updates to 3.5 and then the quality became bad; but then you mention that you updated the library but that the new version is fine. Have you updated again to some other version, or are you still with 3.5 and bad quality videos?

Can you please share some code that generates/writes those videos so I can investigate?

What difference in the pixel value did you observe?

Regards,
Cesar

**Comment by AlexGimo** [comment]
Ok, I'll explain:
I, actually, record two videos:
1. colour video with H264 codec;
2. depth video black and white (0-255) with raw format.

I have been working with accord.video.ffmpeg 3.4.2-alpha to record the videos. First one was ok, while the second had sightly different values between the real one and the one written in the video frame (e.g. pixel value of the bitmap 65, pixel of the frame 70?!). That was a huge problem since depth video needs to be precise.

Updating the nuget package to 3.5.0 the problem with the depth video was resolved meanwhile the colour video became practically meaningless: first frame is ok but then it became more "pixelous" moving to weird colours?!

If you need more information you ask.
Thank you for the interest,
Alex

**Comment by jburnsman** [comment]
Agreed, I see similar behavior. Originally I was using Accord 3.3.0 and using H264 codec. Videos were recording fine. I then updated to Accord 3.5.0 via Nuget and see the same pixelated videos that Alex is seeing. The time value also seems to be compressed. For now I have reverted back to 3.3.0.

I can provide a link to a sample video if that helps.

**Comment by cesarsouza** [comment]
Hi everyone,

I've just uploaded a new pre-release version of the library to NuGet (3.5.1-alpha). Can you please see if this version fixes the issues you were having?

Regards,
Cesar

**Comment by jburnsman** [comment]
Hello Cesar,

I tested the new build 3.5.1-alpha. The video is now being encoded properly and plays back correctly. Thanks for the fix

-Jason

**Comment by cesarsouza** [comment]
Great! Thanks for letting me know!

**Comment by cotzo** [comment]
I have the same issue with MPEG4 codec and even after the update to latest alpha version the quality is bad after the 1st second. I tried also with the H264 code but I get the following exception: "Attempted to read or write protected memory. This is often an indication that other memory is corrupt". Can you please advise? Thanks

**Comment by AlexGimo** [comment]
@cesarsouza I have tested v3.5.2 and works fine. Thank you for the effort.

@cotzo I got the same error while performing operation in the wrong way e.g. try to simultaneously write a frame form different threads or non correct use of bitmaps. Try to check.

**Comment by cotzo** [comment]
@AlexGimo it's not multi threaded and I'm using the same bitmaps as with coded MPEG4 but on H264 it crashes

**Comment by AlexGimo** [comment]
Tried just to guess. Then I don't know :)

**Comment by cotzo** [comment]
@cesarsouza do you have any idea about this issue? Thanks

**Comment by cesarsouza** [comment]
Hi there,

I am also not quite sure why this happens, but when I happened to encounter this issue it was either because I was writing Bitmaps from multiple threads, as AlexGimo mentioned, or when I was trying to write very large images (in 4k resolution) with a frame rate that was too high. Unfortunately I don't have a solution for the latter, besides writing smaller frames or at a slower framerate...

**Comment by cesarsouza** [comment]
Fixed in release 3.6.0.
