### ISSUE TITLE
Decision tree\ random forest - Add support for weight based entropy

### ISSUE THREAD

**Issue by stas-vi** [accord-net/framework#643]
Hi,

Current implementation of C45Learning\RandomForestLearning Learn method, has an input parameter of weights with a summary an all, however the actual implementation ignores this.

Are there any plans of adding weights support? it's a little confusing in it's current state

Thanks.

**Comment by cesarsouza** [comment]
Hi there,

Thanks for opening the issue! Indeed, many of the learning algorithms were ignoring the weights when they didn't support weighted instances instead of notifying the user about the limitation. Soon I might be able to commit some changes to at least throw an exception and update the documentation when this might be the case.

Regarding having instance weights for the Decision Tree, do you know of any paper or other literature indicating how a weighted version of the entropy could be implemented for learning decision trees, such that I could use it as a reference?

Regards,
Cesar

**Comment by cesarsouza** [comment]
This was implemented in https://github.com/accord-net/framework/commit/9bfc5e9b825186cd9ae4d3bd4a6aba34df1a1f9a for #211 and should be available in the next release.

**Comment by cesarsouza** [comment]
Fixed in release 3.8.0. Decision Tree learning algorithms can now take the sample weights in consideration.
