### ISSUE TITLE
Question: (Multiple) Linear Regression on factors

### ISSUE THREAD

**Issue by yufanlu** [accord-net/framework#655]
Hi there,

I am just wondering if there is a way to do Linear Regression on factor/categorical dependent variable(s) along with continuous dependent variable(s)? 

It would be something like the  lm( y ~ factor(x1) + x2) in R.

I've tried codification and transfer the labels, and the use OrdinaryLeastSquares to do the regression. But I don't think I am using the right approach here. Is there an example that I could refer to?

Thank you so much on working on this fantastic project!

**Comment by cesarsouza** [comment]
Hi there,

In order to do linear regression on categorical variables right now, I guess it would be necessary to first pre-process your data to transform the categorical variables into one-hot vectors. I think this is currently possible with the Codification class if you specify [CodificationVariable.Categorical](http://accord-framework.net/docs/html/T_Accord_Statistics_Filters_CodificationVariable.htm) as the columns' [VariableType property](http://accord-framework.net/docs/html/P_Accord_Statistics_Filters_Codification_1_Options_VariableType.htm).

However, I agree that an example is lacking here. I will try to come up with a more recent example on how to  do this, but for now, please see if the following can help:

```csharp
DataTable table = ... // let's say you have your mixed continuous/categorical variables here
var codification = new Codification(table);
codification["variableName1"].VariableType = CodificationVariable.CategoricalWithBaseline;
codification["variableName2"].VariableType = CodificationVariable.Categorical;

// This should transform your variables to one-hot or one-hot with baseline vectors
var resultTable = codification.Apply(table);

// Transform to a double[][] array you can pass to the classifiers
double[][] result = resultTable.ToJagged();
```

Regards,
Cesar

**Comment by yufanlu** [comment]
That is super helpful! Thank you so much!
