### ISSUE TITLE
NaiveBayes 'System.IndexOutOfRangeException' occurred in Accord.Statistics.dll

### ISSUE THREAD

**Issue by dtaylor-530** [accord-net/framework#765]
Hi 
I'm getting the above error on this line

[165]  int[] output = bayes.Decide(inputs); 

in the main form when i run the modeltesting using the sample data.
Also the Accord.Statistics.dll version is 3.6.0.0.

Thanks

**Comment by cesarsouza** [comment]
Hi @dtaylor-530,

Thanks a lot for reporting the issue. The problem is actually in the line

```csharp
            double[][] inputs = table.Get(null, 0, 1).ToJagged();
```

which is retrieving all rows (so, 'null'), and columns 0 (inclusive) until 1 (exclusive) from the table. Unfortunately this means it is retrieving only a single column (column 0). In order to fix the problem, this line needs to be changed to

```csharp
            double[][] inputs = table.Get(null, 0, 2).ToJagged();
```

so that it can select the first two columns instead of just one.

Regards,
Cesar

**Comment by dtaylor-530** [comment]
Thanks perfect. It's fixed.
