### ISSUE TITLE
Binary Labels in ZeroOneLoss

### ISSUE THREAD

**Issue by KonstantinLukaschenko** [accord-net/framework#824]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - [ ] question
  - [x] bug report
  - [ ] feature request

**Issue description**

Hi @cesarsouza,

I'm using a ZeroOneLoss to evaluate a classifier with a 10-fold cross validation. During the cross validation, my holdout data often contains only 2 of _n_ possible classes. The ZeroOneLoss assumes a [binary label](https://github.com/accord-net/framework/blob/98e6d94b43472ed1277f54695eb586ef80b9432c/Sources/Accord.Math/Optimization/Losses/ZeroOneLoss.cs#L146) in such a case. When computing the loss against the predicted values, an [exception](https://github.com/accord-net/framework/blob/98e6d94b43472ed1277f54695eb586ef80b9432c/Sources/Accord.Math/Optimization/Losses/ZeroOneLoss.cs#L185) is thrown if the predicted values are not binary.

For example: `new ZeroOneLoss(new int[] {0, 1}).Loss(new int[] {0, 2})`.

AFAICS, we need to inspect both, the expected and the actual values to determine if binary labels are used or not.

**Comment by cesarsouza** [comment]
Hi @KonstantinLukaschenko,

Thanks a lot for opening the issue! I think you are completely right. If you think you have a solution in mind, please do not hesitate to contribute a pull request to the project, it would be greatly appreciated!

Also, maybe another solution for the cross-validation case would be to use a mechanism where the actual number of classes can be specified instead of being guessed by the implementation, such as for example using a GeneralConfusionMatrix instead:
```csharp
double acc = new GeneralConfusionMatrix(classes: 3, 
    expected: new int[] {0, 1}, 
    predicted: new int[] {0, 2}).Accuracy;
```

Regards,
Cesar

**Comment by KonstantinLukaschenko** [comment]
Hi @cesarsouza,

thanks a lot for your feedback. Please review my latest commit. It

- adds `NumberOfClasses` to `ZeroOneLoss` in favour of `IsBinary`
- enhances number of class inference and normalization
- introduces unit tests for `ZeroOneLoss`

If the commit looks good to you, I'll be happy to create a PR.

Best regards
Konstantin

**Comment by cesarsouza** [comment]
Hi @KonstantinLukaschenko,

Amazing! Thanks a lot for the contribution! Can I only add one suggestion: can you please keep the IsBinary property, but instead, make it return whether ```NumberOfClasses == 2```? In this way we can keep API compatibility in case anyone was using this property in their existing code.

Otherwise, the commit looks great, a PR would be greatly appreciated!

Regards,
Cesar

**Comment by KonstantinLukaschenko** [comment]
The IsBinary property is now restored and pull request created.
