### ISSUE TITLE
Accord.Neuro under .Net Standard 2.0

### ISSUE THREAD

**Issue by oaimac** [accord-net/framework#828]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - [x ] question
  - [ ] bug report
  - [ ] feature request

**Issue description**

The Accord.Neuro library is not available under .Net Standard 2.0 when getting it passing through Nuget.
The Accord .Net Standard project also do not generate it.
Will this library be officially available under .Net Standard 2.0 in a near future ?

Thanks,
Regards,

**Comment by cesarsouza** [comment]
Hi @oaimac,

Thanks for opening the issue. The Accord.Neuro library is not included in the .NET Standard packages because it is going to be eventually replaced with [Keras Sharp](https://github.com/cesarsouza/keras-sharp) in the future. 

However, if you have an already existing project using Accord.Neuro that you would like to use from .Net Standard 2.0, please let me know.

Regards,
Cesar

**Comment by oaimac** [comment]
Hi. Thanks a lot for your answer.
Yes I use it for an existing project. When compiling it manually with Standard 2.0, it seems to work.
So it would be a great help to have an official version for maintenability and usability reasons in time.

Regards,

**Comment by cesarsouza** [comment]
Added in 3.8.0.
