### ISSUE TITLE
Very minor bug in quadratic objective function

### ISSUE THREAD

**Issue by AlexJCross** [accord-net/framework#832]
The `ToString()` throws a `NullReferenceException` when the `QuadraticObjectiveFunction` is instantiated without using the Expression constructor (i.e. instantiated using matrices and vectors) because the [Dictionaries are never initialised](https://github.com/accord-net/framework/blob/development/Sources/Accord.Math/Optimization/QuadraticObjectiveFunction.cs#L372).

I'm open to suggestions on what should be shown but I would propose, say, "6-dimensional Quadratic Objective Function" (clearly we cannot enumerate the whole problem if it is a 1000x1000 matrix!

Thinking about it, perhaps it wouldn't be so bad to do away with those dictionaries altogether. The info seems mostly redundant as one can quite easily back out a string representation from knowledge of the underlying matrix and vector (ignoring zeros). That would make GH-819 easier but let me know if you'd like to keep them.

thanks,
Alex

**Comment by AlexJCross** [comment]
Hi @cesarsouza ,

I'm finishing up on GH-819 and wanted to let you know I've made a few changes to the `QuadraticObjectiveFunction`. They're all pretty minor but I thought I'd better flag them rather than go Rambo and change the codebase. If you'd like me to hold off on adding any of these, please let me know and I'm 100% happy to revert!

---------------

1. **The `ToString()` throws a `NullReferenceException`:** Comment above gives more details.

*I deleted the dictionaries 'quadratic' and 'linear' as it is pretty much entirely duplicate data and were left uninitialised if problems were created using matrices and vectors. Also it really bloated the code for GH-819. Instead, I simply interrogate the matrix/vector directly and generate a string. A minor consequence of this is that the order in which the terms in the string are created is different - it is now sorted in order instead of [the order they were defined](https://stackoverflow.com/questions/9822987/why-does-the-net-dictionary-look-like-it-is-sorted). i.e: quadratic, cross-terms, linear terms, constant.*

```csharp
var f = new QuadraticObjectiveFunction("2x² + xy - y² + 5y");
// before: +2xx +1xy -1yy +5y
// after:   2x² -1y² +1xy +5y
```

2. **The Expressions assume Q is symmetric:** This code compiles and runs fine but creates the wrong quadratic matrix: `var actual1 = new QuadraticObjectiveFunction(() => 2 * y * x - x * y + y * z);`

*I am aware that there is a paragraph in the XML documentation saying this isn't permitted (it has an xy and a yx term in it) but it is hard to spot and shouldn't silently produce incorrect numbers. I only had to add three characters to make it work (+= instead of =) so I did just that!*

3. **Non-symmetric matrices:** Needs error checking or handling or clearer documentation. 

*This is not really being handled and there are inconsistencies with the `QuadraticConstraint` class. The lambda expression approach produces incorrect functions and gradients, the matrix/vector approach produces incorrect gradients and the constraint class handles non-symmetric matrices correctly. Three options here: throw an `Exception` if a non-symmetric matrix is passed in; convert non-symmetric matrices to symmetric matrices upfront (at the cost of memory); or handle non-symmetric matrices correctly like the `QuadraticConstraint` class does (at the expense of speed). Personally, I like option 1 and, for consistency, we should probably do the same in the `QuadraticConstraint`*.*

4. **Changed the default variable names**

*As a consequence of fixing point 1, I realised the string representation is pretty unreadable so I subscripted the default variables. Let me know if you have any objections.*
`before: 4x0x0 +2x1x1 +3x2x2 +3x0x1 +1x0x2 +2x1x2`
`after : 4x₀² +2x₁² +3x₂² +3x₀x₁ +1x₀x₂ +2x₁x₂`

Thanks,
Alex

*On the topic of consistency, I find it super confusing that the `QuadraticObjectiveFunction` evaluates problems in standard quadratic programming form (0.5xQx+dx) but the `QuadraticConstraint` does not include the factor of 0.5. Is this intentional?

**Comment by cesarsouza** [comment]
Hi Alex!

As usual, thanks a lot for the amazing contributions!

1. I believe the dictionaries were there to be able to perform argument/error checks whenever they were combined with constraints defined using lambdas, expressions, or strings. However, since this functionality was never fully completed, and since I had to move from the optimization algorithms into other fields, please feel free to do those modifications!

2 & 3. Those should really have been caught by the method, thanks for that for raising the concern. Additionally, I would say it might be worth to take a look on whether it could be possible to allow the user to pass triangular jagged matrices to specify a symmetric matrix to save some memory and argument checks.

4. This is simply perfect.

Regarding the consistency remark, I _think_ (though I haven't been able to confirm yet, it has been some years) that this had been done this way to accomplish compatibility with R. If you have a better suggestion (even though it might break a few unit tests), please let me know!

Regards,
Cesar

**Comment by AlexJCross** [comment]
Thanks @cesarsouza,

 1. Ok cool. I'll remove them for now - should simplify things a little. If there's functionality that you feel is missing or incomplete feel free to raise an issue and ask me. I can always say no if I can't find the time 🙂
2. (&3) Ok from now on the matrix constructor will throw if not symmetric. I really like your idea about jagged arrays - I'll try to add that - but I will do that in a separate issue so the issues I raise don't get too much scope creep and never get completed!
4. Great. 

Ah I see. Ok that makes sense and I am sure it is the case that R or some R package uses that form. I have never used R myself so know as much about that language as I do APL! However, I did have a quick google of the phrase `quadratic constraint optimization` and the links [here (Matlab)](http://uk.mathworks.com/help/optim/ug/linear-or-quadratic-problem-with-quadratic-constraints.html), [here (an R package?)](https://cran.r-project.org/web/packages/ROI/ROI.pdf#page23), [here (Wikipedia)](https://en.m.wikipedia.org/wiki/Quadratically_constrained_quadratic_program) plus 3 others use the same form - 0.5xQx - as the quadratic objective function. It's very easy to see how someone working with a quadratically constrained quadratic objective function will make a mistake when setting up this problem given Accord uses different conventions for the same representation. 

If you want me to, I can make them consistent but I'm also totally happy to leave it if you prefer. The only sensible way I can think to do it would be to overload the constructor (drop the ObjectiveFunction from it) and obsolete the old one. 

ps - full disclosure. I did find [one link](https://www.inverseproblem.co.nz/OPTI/index.php/Probs/QCQP) that does it the way Accord does currently so very happy to not change this!

**Comment by cesarsouza** [comment]
Hi @AlexJCross,

Thanks a lot for the follow up. I think that the most important feature would be to be compatible with R, and secondly with MATLAB/Octave. The most prominent package for quadratic programming in R is surely  Berwin A. Turlach's [QuadProg](https://cran.r-project.org/web/packages/quadprog/quadprog.pdf). If this is the form used by this package, then surely we should make this change. It has been some years since I last touched the inner workings of the optimization algorithms, and I think you have more experience on them than me, so please feel free to update them in a way that would make more sense to the common user of the quadratic optimization interfaces 👍 

Regards,
Cesar
