### ISSUE TITLE
net standard 1.4 support

### ISSUE THREAD

**Issue by bulente** [accord-net/framework#839]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - [X] question
  - [ ] bug report
  - [ ] feature request

**Issue description**

According to 3.7.0 release notes, framework now supports .net standard 1.4 version but I can't add nuget packages to my visual studio project and the error shows it only supports .net standard 2.0 version. 

Is it supporting 1.4 version?

**Comment by cesarsouza** [comment]
Hi @bulente,

While it is true that the framework supports .NET Standard 1.4, not all libraries from the framework can be used from this platform right now. For instance, Accord.Imaging, Vision, Video, FFMPEG, Neuro, or any others which might depend on System.Windows.Forms and System.Windows.Drawing might not be available, and there aren't any plans to do so at the moment. 

This is mostly because support for System.Drawing in .NET Standard is being accomplished through [CoreCompat.System.Drawing.v2](https://www.nuget.org/packages/CoreCompat.System.Drawing.v2), which for the moment is only available for .NET Standard 2.0.

Thus said, may I ask which packages are you trying to add to your project? If you are not trying to include any of the libraries I listed above, then it should have worked. Please let me know and I will investigate.

Regards,
Cesar

**Comment by bulente** [comment]
Hello Cesar,

I'm trying to add the Accord.Imaging and now I can see your point. Thanks for the reply.
