### ISSUE TITLE
When to use "Accord.Math.Random.Generator.Seed = 0;"

### ISSUE THREAD

**Issue by blaisexen** [accord-net/framework#861]
- [x] question
 
When to use "Accord.Math.Random.Generator.Seed = 0;"

I used it like this: BUT I noticed it slows down the process! OR I did wrong? I'm sorry I'm confused!

```
FileInfo[] files = GetFilesByExtensions(path, ".bmp", ".jpg").ToArray();
for (int i = 0; i < files.Length; i++)
{
//Codes here....
}

Accord.Math.Random.Generator.Seed = 0; //SEED
var surfBow = new BagOfVisualWords<FeatureDescriptor>(new LocalBinaryPattern(), new BinarySplit(36));

Accord.Math.Random.Generator.Seed = 0; //SEED
surfBow.ParallelOptions.MaxDegreeOfParallelism = 1;
bow = surfBow.Learn(dimages.ToArray());

Accord.Math.Random.Generator.Seed = 0; //SEED
var kernel = new ChiSquare();        

foreach (var images in listofimages)
{
Accord.Math.Random.Generator.Seed = 0; //SEED
double[] featureVector = (bow as ITransform<Bitmap, double[]>).Transform(images.fimage);
fvalues.Add(featureVector);
fclassnums.Add(images.fclassnum);
}

Accord.Math.Random.Generator.Seed = 0; //SEED
var svmteacher = new MulticlassSupportVectorLearning<IKernel>()
{
//
}

Accord.Math.Random.Generator.Seed = 0; //SEED
svmteacher.ParallelOptions.MaxDegreeOfParallelism = 1;
ksvm = svmteacher.Learn(fvalues.ToArray(), fclassnums.ToArray());

```
//SVM Ready for Decision or DECIDE

**Comment by cesarsouza** [comment]
Hi @blaisexen,

If you are setting max degree of parallelism to be 1 in all cases, then you can just set the random seed only once, in the start of the execution of your program.

Regards,
Cesar

**Comment by blaisexen** [comment]
@cesarsouza,
.ParallelOptions.MaxDegreeOfParallelism = 1;

What happens if I'm going to set = 2;

Does if effect the process speed? 
because the word "Parallel" means confuse for me to the number to set 1

**Comment by cesarsouza** [comment]
Hi @blaisexen,

Setting MaxDegreeOfParallelism to one means we are forcing the method to be run in a single thread. If you set it to a number higher than zero, like 2, it means the method will be run using at maximum 2 cores in your computer. If you do not set it, or set it to -1, it will automatically use as many cores as your computer has.

The problem, however, is that some methods when run in parallel can become non-deterministic, so in this case, even if you set the random seed to a fixed number you might not be able to obtain always the same values between different runs of your program.

If I understood correctly, you are setting the random seed because you want to make it output always the same values every time you run it, is it right?

Regards,
Cesar

**Comment by blaisexen** [comment]
Thank you for the clarification, just what I doubt,

>If I understood correctly, you are setting the random seed because you want to make it output always the same values every time you run it, is it right?
Yes, Right!.
:dancer:
