### ISSUE TITLE
Adding Convolutional Neural Networks (with GPU support)

### ISSUE THREAD

**Issue by AvenSun** [accord-net/framework#92]
Accord.Net framework is always my favorite. 
Thanks for doing such amazing work.
Nowdays deep learning is becoming hotter and hotter, 
I know Accord already does have DBN,
So is it the right time to plan for CNN now ?
the link I found as follows is about CNN in C#, maybe it's a good start.
http://www.codeproject.com/Articles/140631/Convolutional-Neural-Network-MNIST-Workbench
also there's one project named "CUDAFY.NET", it allows easy development of high performance GPU applications in C#.
http://cudafy.codeplex.com/ <_>

**Comment by cesarsouza** [comment]
Hi Adesun!

Thanks for registering this issue. Indeed I want to implement CNNs as soon as possible. The problem is that the current AForge.NET interfaces for defining networks and learning algorithms would be very inefficient for creating a CNN right now. As such, I am planning to start working on this issue after I finish issue #70.

**Comment by Adesun** [comment]
I'm so looking forward to it !
It would be one big good news for fans of Accord.Net.
thanks for your efforts!

**Comment by Ph47** [comment]
Good day Cesarsouza!
How about implementing CNN at this time? It is really wanted feature.

**Comment by lostmsu** [comment]
Just wanted to leave my 5 cents on this issue. It seems, that one of the most popular deep learning frameworks is caffe+theano (which, sadly, do not easily run on Windows). Caffe has a very convenient library of pretrained DNNs: http://caffe.berkeleyvision.org/model_zoo.html
It would be nice to be able to reuse it in whatever is coming in for CNNs and deep learning in Accord.

**Comment by jbruening** [comment]
@lostmsu, @cesarsouza I have a library which I've created specifically for parsing text format protocol buffer files, which caffe uses for their models.  I couldn't find any specific libraries for protobuf in .net that supported reading the text format.

https://github.com/jbruening/ProtoTxt.Net

The [test](https://github.com/jbruening/ProtoTxt.Net/tree/master/src/Tests/Integration/Caffe) that I have is caffe.proto generated classes reading one of the googlenet files.

**Comment by merceyz** [comment]
@cesarsouza any ETA on the arrival of CNN implementation as issue #70 is now closed?

**Comment by XeonMan** [comment]
Any news on CNN implementation in Accord.NET?

**Comment by XinliZ** [comment]
Expecting CNN, same here.

**Comment by herodata** [comment]
any news ?
:)

**Comment by cesarsouza** [comment]
Hello everyone! 

I know it has been a while since this issue was updated. However, this hiatus had a justification. In the mean time, I have been experimenting with different ways to rework the existing neural network's library in order to leverage existing cutting edge implementations such as Caffe and Theano.

While I was initially inclined towards writing a C# wrapper to Caffe (and had actually started working in this direction), I've come to know a few weeks ago that Miguel de Icaza (of Mono and Gnome fame) has decided to give it a try trying encapsulate TensorFlow in C# through the [TensorFlowSharp project](https://github.com/migueldeicaza/TensorFlowSharp). 

I personally believe that TensorFlow has a more future-proof profile in contrast to Caffe and Theano, and as such, the current plan is to aid the development of TensorFlowSharp and eventually develop an API in Accord.NET similar to what Keras currently provides to TensorFlow and Theano in Python.

Any help in such endeavor (or any comments you might have in this matter) would be more than welcome.

One of the biggest issues right now (at least for me) is coming up with clear instructions on how to setup and build the project on Windows (https://github.com/migueldeicaza/TensorFlowSharp/issues/21), as for the moment most of the development is being done under OS X. 

Regards,
Cesar

**Comment by JimSEOW** [comment]
@cesarsouza  The Windows DLL is now available through Nuget. A recent check of SimpleTest, show [most ](https://github.com/migueldeicaza/TensorFlowSharp/issues/64)of the examples passed.  It would be great to see the community here to start exploring the TensorflowSharp in Window e.g. 64bit environment

**Comment by lostmsu** [comment]
@cesarsouza and everyone. I've recently came up by https://github.com/cbovar/ConvNetSharp for a short-term solution. It has descent interface and supports GPU. Not very optimized yet though. You might want to check Lost Tech's fork though if you need more perf: https://github.com/losttech/ConvNetSharp/

**Comment by Michael8080** [comment]
Hi cesarsouza you are doing a great job and we are thankful for your great effort,
is there any progress about cnn? thank you

**Comment by Vittel** [comment]
+1
