### ISSUE TITLE
Accord.Video.FFMPEG.x64.dll  file not found

### ISSUE THREAD

**Issue by opuspop** [accord-net/framework#928]
**What would you like to submit?** (put an 'x' inside the bracket that applies)

  - [ x] question
  - [ ] bug report
  - [ ] feature request

Hi, 

I have this code that which is a test before I implement the video player in a main app I am working on (x64, .Net 4.6).
(by the way I am very new to Visual Studio and C# so please bare with me)

            public Form1()
            {
                InitializeComponent();
            }

            private void button1_Click(object sender, EventArgs e)
            {
                OpenFileDialog openFileDialog1 = new OpenFileDialog();
                if (openFileDialog1.ShowDialog() == DialogResult.OK)
                {
                    string fileName = openFileDialog1.FileName;
                    VideoFileReader reader = new VideoFileReader();
                    reader.Open(fileName);
                    for (int m = 0; m < 30; m++)
                    {
                        Bitmap videoFrame = reader.ReadVideoFrame();
                        pictureBox1.Image = videoFrame;
                    }
                    label2.Text = reader.FrameCount.ToString();
                    label3.Text = reader.Width.ToString();
                    label4.Text = reader.Height.ToString();
                    label5.Text = reader.BitRate.ToString();
                }
            }

I imported Accord.Video.FFMPEG.X64 with NuGet
![capture d ecran 2017-10-01 a 15 23 41](https://user-images.githubusercontent.com/5308540/31058331-0124d8c0-a6c0-11e7-9cf2-f8fb51d6b546.png)

![capture d ecran 2017-10-01 a 15 24 48](https://user-images.githubusercontent.com/5308540/31058337-2196607e-a6c0-11e7-9eab-966b3e0e1a71.png)

When I build the application, It works fine on my machine but copying the folder on another machine  and starting the app I get an error saying it can't load the file assembly Accord.Video.FFMPEG.x64.dll although it is in the folder with the app.
![capture](https://user-images.githubusercontent.com/5308540/31058382-a2226b3e-a6c0-11e7-87f4-09b4059ba7d1.PNG)

Both machines have .Net 4.6, 64bit Os, Windows 7. 

*** Update: does the same with .Net 4.0. works on my machine but not on others.

Any idea why I get an error like this?

Thanks

**Comment by cesarsouza** [comment]
Hi @opuspop,

Thanks for opening the issue. This is very likely because the other machine does not have Visual Studio's C++ runtime redistributable installed. 

However, I am not completely sure about which runtime is currently needed for the particular version of the framework you are using because the framework runtimes have only been standardized very recently, and this standardization has not been included in any release yet.

As such, please start by trying to install VS2017's redistributable package. If it doesn't work, then please try to install VS2015's as well. You can find them in the links below:
 - VS2017: https://go.microsoft.com/fwlink/?LinkId=746572
 - VS2015: https://www.microsoft.com/en-us/download/details.aspx?id=48145

Please let me know if it works!

Regards,
Cesar

**Comment by opuspop** [comment]
Thank you, I will try this immediately.

**Comment by heltonbiker** [comment]
Same problem here, installing VCRedist2015 32 bits solved the issue on the client machine.
