### ISSUE TITLE
Add an Example for HiddenMarkovModel(TDistribution, TObservation) Class

### ISSUE THREAD

**Issue by isaactarume** [accord-net/framework#965]
Thanks Cesar this is quite fascinating, you wrote

The following example shows how hidden Markov models trained using Maximum Likelihood Learning can be used in the context of fraud analysis, in which we actually know in advance the class labels for each state in the sequences we are trying to learn:

You say above that you used the ML because we know already about class labels. The assumption of using the ML here instead of the Expectation Maximization like the Baumwelch, is that you have in the other example is because we are assuming the data variables observed are complete. But in most cases we know there is always the hidden or missing data in our observation such that the observed data will not always adequately model the distribution from which the data came from.  So in the case of fraud there can be easily other 20 or even 100 variables about one transaction which we cannot observe although we know the label class.

Now Will like to know what do you think about that and then using the EM instead how would u implement it with known class labels?

Help Topic: http://accord-framework.net/docs/html/T_Accord_Statistics_Models_Markov_HiddenMarkovModel_2.htm

**Comment by cesarsouza** [comment]
Hi @isaactarume,

Thanks for the question! I suppose a good model to be used in this case would be a [partially observed Markov model](https://www.hds.utc.fr/~tdenoeux/dokuwiki/_media/en/publi/ps_hmm_conf.pdf).

It should be possible to modify Baum-Welch or Viterbi learning to consider the observed state labels when they are available, but perform consider all state possibilities when they are not. I guess that the easiest way to implement a learning algorithm for those kind of models would be to start with [Viterbi learning](http://accord-framework.net/docs/html/T_Accord_Statistics_Models_Markov_Learning_ViterbiLearning.htm), then modify the Viterbi decoding to consider soft-labels as is mentioned in section 2.3 of that paper. 

Since Viterbi learning is just iterative MLE using the class labels predicted by the model (i.e. by the Viterbi decoding algorithm), it wouldn't require any changes to the learning algorithm itself, just to the decoding part.

The algorithm will not really be EM, though. The relationship of the Viterbi algorithm to Baum-Welch is similar to the K-Means algorithm to EM (for Gaussian Mixture Models).

Regards,
Cesar
